// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import webref "github.com/brendoncarroll/webfs/pkg/webref"
import wrds "github.com/brendoncarroll/webfs/pkg/wrds"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Object struct {
	// Types that are valid to be assigned to Value:
	//	*Object_File
	//	*Object_Dir
	//	*Object_Volume
	Value                isObject_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{0}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

type isObject_Value interface {
	isObject_Value()
}

type Object_File struct {
	File *File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type Object_Dir struct {
	Dir *Dir `protobuf:"bytes,2,opt,name=dir,proto3,oneof"`
}

type Object_Volume struct {
	Volume *VolumeSpec `protobuf:"bytes,3,opt,name=volume,proto3,oneof"`
}

func (*Object_File) isObject_Value() {}

func (*Object_Dir) isObject_Value() {}

func (*Object_Volume) isObject_Value() {}

func (m *Object) GetValue() isObject_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Object) GetFile() *File {
	if x, ok := m.GetValue().(*Object_File); ok {
		return x.File
	}
	return nil
}

func (m *Object) GetDir() *Dir {
	if x, ok := m.GetValue().(*Object_Dir); ok {
		return x.Dir
	}
	return nil
}

func (m *Object) GetVolume() *VolumeSpec {
	if x, ok := m.GetValue().(*Object_Volume); ok {
		return x.Volume
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Object) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Object_OneofMarshaler, _Object_OneofUnmarshaler, _Object_OneofSizer, []interface{}{
		(*Object_File)(nil),
		(*Object_Dir)(nil),
		(*Object_Volume)(nil),
	}
}

func _Object_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Object)
	// Value
	switch x := m.Value.(type) {
	case *Object_File:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.File); err != nil {
			return err
		}
	case *Object_Dir:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dir); err != nil {
			return err
		}
	case *Object_Volume:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Volume); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Object.Value has unexpected type %T", x)
	}
	return nil
}

func _Object_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Object)
	switch tag {
	case 1: // Value.file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.Value = &Object_File{msg}
		return true, err
	case 2: // Value.dir
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Dir)
		err := b.DecodeMessage(msg)
		m.Value = &Object_Dir{msg}
		return true, err
	case 3: // Value.volume
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VolumeSpec)
		err := b.DecodeMessage(msg)
		m.Value = &Object_Volume{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Object_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Object)
	// Value
	switch x := m.Value.(type) {
	case *Object_File:
		s := proto.Size(x.File)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Object_Dir:
		s := proto.Size(x.Dir)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Object_Volume:
		s := proto.Size(x.Volume)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type File struct {
	Tree                 *wrds.Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	Size                 uint64     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetTree() *wrds.Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Dir struct {
	Tree                 *wrds.Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}
func (*Dir) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{2}
}
func (m *Dir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dir.Unmarshal(m, b)
}
func (m *Dir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dir.Marshal(b, m, deterministic)
}
func (dst *Dir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dir.Merge(dst, src)
}
func (m *Dir) XXX_Size() int {
	return xxx_messageInfo_Dir.Size(m)
}
func (m *Dir) XXX_DiscardUnknown() {
	xxx_messageInfo_Dir.DiscardUnknown(m)
}

var xxx_messageInfo_Dir proto.InternalMessageInfo

func (m *Dir) GetTree() *wrds.Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type DirEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Object               *Object  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirEntry) Reset()         { *m = DirEntry{} }
func (m *DirEntry) String() string { return proto.CompactTextString(m) }
func (*DirEntry) ProtoMessage()    {}
func (*DirEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{3}
}
func (m *DirEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirEntry.Unmarshal(m, b)
}
func (m *DirEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirEntry.Marshal(b, m, deterministic)
}
func (dst *DirEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirEntry.Merge(dst, src)
}
func (m *DirEntry) XXX_Size() int {
	return xxx_messageInfo_DirEntry.Size(m)
}
func (m *DirEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DirEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DirEntry proto.InternalMessageInfo

func (m *DirEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirEntry) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type VolumeSpec struct {
	// Types that are valid to be assigned to CellSpec:
	//	*VolumeSpec_Http
	CellSpec             isVolumeSpec_CellSpec `protobuf_oneof:"cell_spec"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VolumeSpec) Reset()         { *m = VolumeSpec{} }
func (m *VolumeSpec) String() string { return proto.CompactTextString(m) }
func (*VolumeSpec) ProtoMessage()    {}
func (*VolumeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{4}
}
func (m *VolumeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSpec.Unmarshal(m, b)
}
func (m *VolumeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSpec.Marshal(b, m, deterministic)
}
func (dst *VolumeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSpec.Merge(dst, src)
}
func (m *VolumeSpec) XXX_Size() int {
	return xxx_messageInfo_VolumeSpec.Size(m)
}
func (m *VolumeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSpec proto.InternalMessageInfo

type isVolumeSpec_CellSpec interface {
	isVolumeSpec_CellSpec()
}

type VolumeSpec_Http struct {
	Http *HTTPCellSpec `protobuf:"bytes,1,opt,name=http,proto3,oneof"`
}

func (*VolumeSpec_Http) isVolumeSpec_CellSpec() {}

func (m *VolumeSpec) GetCellSpec() isVolumeSpec_CellSpec {
	if m != nil {
		return m.CellSpec
	}
	return nil
}

func (m *VolumeSpec) GetHttp() *HTTPCellSpec {
	if x, ok := m.GetCellSpec().(*VolumeSpec_Http); ok {
		return x.Http
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*VolumeSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _VolumeSpec_OneofMarshaler, _VolumeSpec_OneofUnmarshaler, _VolumeSpec_OneofSizer, []interface{}{
		(*VolumeSpec_Http)(nil),
	}
}

func _VolumeSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*VolumeSpec)
	// cell_spec
	switch x := m.CellSpec.(type) {
	case *VolumeSpec_Http:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Http); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("VolumeSpec.CellSpec has unexpected type %T", x)
	}
	return nil
}

func _VolumeSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*VolumeSpec)
	switch tag {
	case 1: // cell_spec.http
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HTTPCellSpec)
		err := b.DecodeMessage(msg)
		m.CellSpec = &VolumeSpec_Http{msg}
		return true, err
	default:
		return false, nil
	}
}

func _VolumeSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*VolumeSpec)
	// cell_spec
	switch x := m.CellSpec.(type) {
	case *VolumeSpec_Http:
		s := proto.Size(x.Http)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Commit struct {
	ObjectRef            *webref.Ref `protobuf:"bytes,1,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	Options              *Options    `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{5}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (dst *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(dst, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetObjectRef() *webref.Ref {
	if m != nil {
		return m.ObjectRef
	}
	return nil
}

func (m *Commit) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Volume Options
type Options struct {
	DataOpts             *webref.Options `protobuf:"bytes,1,opt,name=data_opts,json=dataOpts,proto3" json:"data_opts,omitempty"`
	MetadataOpts         *webref.Options `protobuf:"bytes,2,opt,name=metadata_opts,json=metadataOpts,proto3" json:"metadata_opts,omitempty"`
	StoreSpecs           []*StoreSpec    `protobuf:"bytes,3,rep,name=store_specs,json=storeSpecs,proto3" json:"store_specs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{6}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (dst *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(dst, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetDataOpts() *webref.Options {
	if m != nil {
		return m.DataOpts
	}
	return nil
}

func (m *Options) GetMetadataOpts() *webref.Options {
	if m != nil {
		return m.MetadataOpts
	}
	return nil
}

func (m *Options) GetStoreSpecs() []*StoreSpec {
	if m != nil {
		return m.StoreSpecs
	}
	return nil
}

type StoreSpec struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Types that are valid to be assigned to Spec:
	//	*StoreSpec_Http
	//	*StoreSpec_Ipfs
	Spec                 isStoreSpec_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StoreSpec) Reset()         { *m = StoreSpec{} }
func (m *StoreSpec) String() string { return proto.CompactTextString(m) }
func (*StoreSpec) ProtoMessage()    {}
func (*StoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_b78ab680ecd13d94, []int{7}
}
func (m *StoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreSpec.Unmarshal(m, b)
}
func (m *StoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreSpec.Marshal(b, m, deterministic)
}
func (dst *StoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreSpec.Merge(dst, src)
}
func (m *StoreSpec) XXX_Size() int {
	return xxx_messageInfo_StoreSpec.Size(m)
}
func (m *StoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_StoreSpec proto.InternalMessageInfo

func (m *StoreSpec) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type isStoreSpec_Spec interface {
	isStoreSpec_Spec()
}

type StoreSpec_Http struct {
	Http *HTTPStoreSpec `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type StoreSpec_Ipfs struct {
	Ipfs *IPFSStoreSpec `protobuf:"bytes,3,opt,name=ipfs,proto3,oneof"`
}

func (*StoreSpec_Http) isStoreSpec_Spec() {}

func (*StoreSpec_Ipfs) isStoreSpec_Spec() {}

func (m *StoreSpec) GetSpec() isStoreSpec_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *StoreSpec) GetHttp() *HTTPStoreSpec {
	if x, ok := m.GetSpec().(*StoreSpec_Http); ok {
		return x.Http
	}
	return nil
}

func (m *StoreSpec) GetIpfs() *IPFSStoreSpec {
	if x, ok := m.GetSpec().(*StoreSpec_Ipfs); ok {
		return x.Ipfs
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StoreSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StoreSpec_OneofMarshaler, _StoreSpec_OneofUnmarshaler, _StoreSpec_OneofSizer, []interface{}{
		(*StoreSpec_Http)(nil),
		(*StoreSpec_Ipfs)(nil),
	}
}

func _StoreSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StoreSpec)
	// spec
	switch x := m.Spec.(type) {
	case *StoreSpec_Http:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Http); err != nil {
			return err
		}
	case *StoreSpec_Ipfs:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ipfs); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StoreSpec.Spec has unexpected type %T", x)
	}
	return nil
}

func _StoreSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StoreSpec)
	switch tag {
	case 2: // spec.http
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HTTPStoreSpec)
		err := b.DecodeMessage(msg)
		m.Spec = &StoreSpec_Http{msg}
		return true, err
	case 3: // spec.ipfs
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IPFSStoreSpec)
		err := b.DecodeMessage(msg)
		m.Spec = &StoreSpec_Ipfs{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StoreSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StoreSpec)
	// spec
	switch x := m.Spec.(type) {
	case *StoreSpec_Http:
		s := proto.Size(x.Http)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StoreSpec_Ipfs:
		s := proto.Size(x.Ipfs)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Object)(nil), "webfs.Object")
	proto.RegisterType((*File)(nil), "webfs.File")
	proto.RegisterType((*Dir)(nil), "webfs.Dir")
	proto.RegisterType((*DirEntry)(nil), "webfs.DirEntry")
	proto.RegisterType((*VolumeSpec)(nil), "webfs.VolumeSpec")
	proto.RegisterType((*Commit)(nil), "webfs.Commit")
	proto.RegisterType((*Options)(nil), "webfs.Options")
	proto.RegisterType((*StoreSpec)(nil), "webfs.StoreSpec")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_objects_b78ab680ecd13d94) }

var fileDescriptor_objects_b78ab680ecd13d94 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x93, 0xee, 0x76, 0x93, 0x7d, 0x6b, 0x6c, 0x1d, 0x44, 0x42, 0x0e, 0x52, 0x57, 0x0a,
	0xa1, 0xca, 0x82, 0xd5, 0x93, 0x07, 0x0f, 0x69, 0x1a, 0xe2, 0xa9, 0x65, 0x12, 0x7a, 0xf0, 0x60,
	0xd8, 0x24, 0x6f, 0x71, 0x64, 0x37, 0x33, 0xcc, 0x4c, 0xad, 0x7a, 0x13, 0xff, 0x11, 0xff, 0x54,
	0x99, 0x99, 0xb7, 0x6d, 0x05, 0xa1, 0xb7, 0x97, 0xf7, 0xfd, 0xbc, 0x5f, 0xdf, 0x9d, 0xc0, 0x40,
	0xae, 0xbf, 0xe2, 0xc6, 0x9a, 0x42, 0x69, 0x69, 0x25, 0xdb, 0xbf, 0xc1, 0x75, 0x65, 0x46, 0x60,
	0x35, 0x62, 0x48, 0x8d, 0x52, 0x8d, 0x15, 0x85, 0x87, 0xc6, 0x4a, 0x8d, 0x46, 0xe1, 0x86, 0xf8,
	0xd1, 0xc1, 0x06, 0xeb, 0xfa, 0x5e, 0x22, 0xff, 0xd5, 0x85, 0xe4, 0xc2, 0xb7, 0x64, 0x2f, 0x20,
	0xae, 0x44, 0x8d, 0xc3, 0xee, 0x51, 0x77, 0x9c, 0x9d, 0x66, 0x85, 0x6f, 0x5d, 0xcc, 0x44, 0x8d,
	0xf3, 0x0e, 0xf7, 0x12, 0x7b, 0x0e, 0xd1, 0x56, 0xe8, 0xe1, 0x9e, 0x27, 0x80, 0x88, 0xa9, 0xd0,
	0xf3, 0x0e, 0x77, 0x02, 0x7b, 0x05, 0xc9, 0x37, 0x59, 0x5f, 0x37, 0x38, 0x8c, 0x3c, 0xf2, 0x84,
	0x90, 0x2b, 0x9f, 0x5c, 0x28, 0xdc, 0xcc, 0x3b, 0x9c, 0x90, 0x49, 0x0f, 0xf6, 0xaf, 0xca, 0xfa,
	0x1a, 0xf3, 0xf7, 0x10, 0xcf, 0x42, 0xf7, 0xd8, 0xdd, 0x41, 0x0b, 0x40, 0x71, 0xa3, 0xb7, 0xa6,
	0x58, 0x6a, 0x44, 0xee, 0xf3, 0x8c, 0x41, 0x6c, 0xc4, 0x4f, 0xf4, 0xe3, 0x63, 0xee, 0xe3, 0xfc,
	0x18, 0xa2, 0xa9, 0xd0, 0x0f, 0x95, 0xe6, 0xe7, 0xd0, 0x9f, 0x0a, 0x7d, 0xbe, 0xb3, 0xfa, 0x87,
	0x6b, 0xb3, 0x2b, 0x9b, 0xc0, 0xa6, 0xdc, 0xc7, 0xec, 0x18, 0x92, 0x60, 0x2c, 0xdd, 0x36, 0xa0,
	0xc5, 0x83, 0x35, 0x9c, 0xc4, 0xfc, 0x03, 0xc0, 0xdd, 0x29, 0xec, 0x25, 0xc4, 0x5f, 0xac, 0x55,
	0x34, 0x74, 0x50, 0xcc, 0x97, 0xcb, 0xcb, 0x33, 0xac, 0x6b, 0xba, 0xd3, 0x8b, 0x93, 0x0c, 0x52,
	0xe7, 0xf9, 0xca, 0x99, 0x9e, 0x7f, 0x86, 0xe4, 0x4c, 0x36, 0x8d, 0xb0, 0xec, 0x04, 0x20, 0xf4,
	0x5c, 0x69, 0xac, 0xee, 0x5b, 0xee, 0xbe, 0x1e, 0xc7, 0x8a, 0xa7, 0x41, 0xe6, 0x58, 0xb1, 0x31,
	0xf4, 0xa4, 0xb2, 0x42, 0xee, 0x0c, 0x6d, 0xf7, 0xb8, 0xdd, 0x2e, 0x64, 0x79, 0x2b, 0xe7, 0x7f,
	0xba, 0xd0, 0xa3, 0x24, 0x7b, 0x0d, 0xe9, 0xb6, 0xb4, 0xe5, 0x4a, 0x2a, 0x6b, 0x68, 0xc0, 0x41,
	0x3b, 0xa0, 0x2d, 0xec, 0x3b, 0xe2, 0x42, 0x59, 0xc3, 0xde, 0xc1, 0xa0, 0x41, 0x5b, 0xde, 0x55,
	0xec, 0xfd, 0xbf, 0xe2, 0x51, 0x4b, 0xf9, 0xaa, 0x37, 0x90, 0xf9, 0x27, 0xe6, 0xaf, 0x33, 0xc3,
	0xe8, 0x28, 0x1a, 0x67, 0xa7, 0x87, 0xb4, 0xdd, 0xc2, 0x29, 0xce, 0x0b, 0x0e, 0xa6, 0x0d, 0x4d,
	0xfe, 0xbb, 0x0b, 0xe9, 0xad, 0xc2, 0x9e, 0x41, 0xa2, 0x34, 0x56, 0xe2, 0x3b, 0x7d, 0x0d, 0xfa,
	0xc5, 0x4e, 0xc8, 0xda, 0xb0, 0xc5, 0x53, 0xea, 0xe8, 0x0c, 0xbe, 0xad, 0x6d, 0x1d, 0x76, 0xac,
	0x50, 0x95, 0xa1, 0x27, 0xd7, 0xb2, 0x1f, 0x2f, 0x67, 0x8b, 0x7f, 0x58, 0xc7, 0x4c, 0x12, 0x88,
	0xdd, 0xaa, 0x93, 0xfe, 0xa7, 0xa4, 0x91, 0x5b, 0xac, 0xcd, 0x3a, 0xf1, 0xff, 0x83, 0xb7, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xfb, 0xe6, 0x1d, 0x59, 0x03, 0x00, 0x00,
}
