// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import webref "github.com/brendoncarroll/webfs/pkg/webref"
import wrds "github.com/brendoncarroll/webfs/pkg/wrds"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Object struct {
	// Types that are valid to be assigned to Value:
	//	*Object_File
	//	*Object_Dir
	//	*Object_Cell
	Value                isObject_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{0}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (dst *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(dst, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

type isObject_Value interface {
	isObject_Value()
}

type Object_File struct {
	File *File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type Object_Dir struct {
	Dir *Dir `protobuf:"bytes,2,opt,name=dir,proto3,oneof"`
}

type Object_Cell struct {
	Cell *CellSpec `protobuf:"bytes,3,opt,name=cell,proto3,oneof"`
}

func (*Object_File) isObject_Value() {}

func (*Object_Dir) isObject_Value() {}

func (*Object_Cell) isObject_Value() {}

func (m *Object) GetValue() isObject_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Object) GetFile() *File {
	if x, ok := m.GetValue().(*Object_File); ok {
		return x.File
	}
	return nil
}

func (m *Object) GetDir() *Dir {
	if x, ok := m.GetValue().(*Object_Dir); ok {
		return x.Dir
	}
	return nil
}

func (m *Object) GetCell() *CellSpec {
	if x, ok := m.GetValue().(*Object_Cell); ok {
		return x.Cell
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Object) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Object_OneofMarshaler, _Object_OneofUnmarshaler, _Object_OneofSizer, []interface{}{
		(*Object_File)(nil),
		(*Object_Dir)(nil),
		(*Object_Cell)(nil),
	}
}

func _Object_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Object)
	// Value
	switch x := m.Value.(type) {
	case *Object_File:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.File); err != nil {
			return err
		}
	case *Object_Dir:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dir); err != nil {
			return err
		}
	case *Object_Cell:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cell); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Object.Value has unexpected type %T", x)
	}
	return nil
}

func _Object_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Object)
	switch tag {
	case 1: // Value.file
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.Value = &Object_File{msg}
		return true, err
	case 2: // Value.dir
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Dir)
		err := b.DecodeMessage(msg)
		m.Value = &Object_Dir{msg}
		return true, err
	case 3: // Value.cell
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CellSpec)
		err := b.DecodeMessage(msg)
		m.Value = &Object_Cell{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Object_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Object)
	// Value
	switch x := m.Value.(type) {
	case *Object_File:
		s := proto.Size(x.File)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Object_Dir:
		s := proto.Size(x.Dir)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Object_Cell:
		s := proto.Size(x.Cell)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type File struct {
	Tree                 *wrds.Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	Size                 uint64     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetTree() *wrds.Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Dir struct {
	Tree                 *wrds.Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}
func (*Dir) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{2}
}
func (m *Dir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dir.Unmarshal(m, b)
}
func (m *Dir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dir.Marshal(b, m, deterministic)
}
func (dst *Dir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dir.Merge(dst, src)
}
func (m *Dir) XXX_Size() int {
	return xxx_messageInfo_Dir.Size(m)
}
func (m *Dir) XXX_DiscardUnknown() {
	xxx_messageInfo_Dir.DiscardUnknown(m)
}

var xxx_messageInfo_Dir proto.InternalMessageInfo

func (m *Dir) GetTree() *wrds.Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type DirEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Object               *Object  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirEntry) Reset()         { *m = DirEntry{} }
func (m *DirEntry) String() string { return proto.CompactTextString(m) }
func (*DirEntry) ProtoMessage()    {}
func (*DirEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{3}
}
func (m *DirEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirEntry.Unmarshal(m, b)
}
func (m *DirEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirEntry.Marshal(b, m, deterministic)
}
func (dst *DirEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirEntry.Merge(dst, src)
}
func (m *DirEntry) XXX_Size() int {
	return xxx_messageInfo_DirEntry.Size(m)
}
func (m *DirEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DirEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DirEntry proto.InternalMessageInfo

func (m *DirEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirEntry) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type CellSpec struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellSpec) Reset()         { *m = CellSpec{} }
func (m *CellSpec) String() string { return proto.CompactTextString(m) }
func (*CellSpec) ProtoMessage()    {}
func (*CellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{4}
}
func (m *CellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellSpec.Unmarshal(m, b)
}
func (m *CellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellSpec.Marshal(b, m, deterministic)
}
func (dst *CellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellSpec.Merge(dst, src)
}
func (m *CellSpec) XXX_Size() int {
	return xxx_messageInfo_CellSpec.Size(m)
}
func (m *CellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CellSpec proto.InternalMessageInfo

func (m *CellSpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CellSpec) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

// Volume Options
type Options struct {
	DataOpts             *webref.Options `protobuf:"bytes,1,opt,name=data_opts,json=dataOpts,proto3" json:"data_opts,omitempty"`
	MetadataOpts         *webref.Options `protobuf:"bytes,2,opt,name=metadata_opts,json=metadataOpts,proto3" json:"metadata_opts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{5}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (dst *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(dst, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetDataOpts() *webref.Options {
	if m != nil {
		return m.DataOpts
	}
	return nil
}

func (m *Options) GetMetadataOpts() *webref.Options {
	if m != nil {
		return m.MetadataOpts
	}
	return nil
}

type Volume struct {
	ObjectRef            *webref.Ref `protobuf:"bytes,1,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	Options              *Options    `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_objects_db25a09fdb3c25e7, []int{6}
}
func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (dst *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(dst, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetObjectRef() *webref.Ref {
	if m != nil {
		return m.ObjectRef
	}
	return nil
}

func (m *Volume) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*Object)(nil), "webfs.Object")
	proto.RegisterType((*File)(nil), "webfs.File")
	proto.RegisterType((*Dir)(nil), "webfs.Dir")
	proto.RegisterType((*DirEntry)(nil), "webfs.DirEntry")
	proto.RegisterType((*CellSpec)(nil), "webfs.CellSpec")
	proto.RegisterType((*Options)(nil), "webfs.Options")
	proto.RegisterType((*Volume)(nil), "webfs.Volume")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_objects_db25a09fdb3c25e7) }

var fileDescriptor_objects_db25a09fdb3c25e7 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0xfd, 0x21, 0xcb, 0xd2, 0xd8, 0x6e, 0x61, 0x0f, 0xc5, 0xf8, 0x50, 0x5a, 0x81, 0xc1,
	0x94, 0xa2, 0x43, 0x5b, 0x7a, 0xc8, 0xd1, 0xb1, 0x8d, 0x6f, 0x86, 0x4d, 0xf0, 0x21, 0x87, 0x18,
	0x59, 0x1a, 0x85, 0x0d, 0x2b, 0xad, 0xd8, 0x5d, 0x63, 0x9c, 0xfc, 0xf3, 0x61, 0x3f, 0x94, 0xe4,
	0x10, 0xc8, 0x6d, 0xb4, 0xef, 0xf7, 0xde, 0xcc, 0xce, 0x0a, 0x26, 0xe2, 0xf8, 0x88, 0xb9, 0x56,
	0x69, 0x23, 0x85, 0x16, 0x64, 0x70, 0xc6, 0x63, 0xa9, 0x66, 0xa0, 0x25, 0xa2, 0x3b, 0x9a, 0xc5,
	0x12, 0x4b, 0x57, 0x26, 0xcf, 0x10, 0xee, 0x2c, 0x4e, 0x7e, 0x42, 0x50, 0x32, 0x8e, 0xd3, 0xee,
	0x8f, 0xee, 0x62, 0xf4, 0x67, 0x94, 0x5a, 0x5b, 0xba, 0x61, 0x1c, 0xb7, 0x1d, 0x6a, 0x25, 0xf2,
	0x1d, 0xfa, 0x05, 0x93, 0xd3, 0x9e, 0x25, 0xc0, 0x13, 0x2b, 0x26, 0xb7, 0x1d, 0x6a, 0x04, 0x32,
	0x87, 0x20, 0x47, 0xce, 0xa7, 0x7d, 0x0b, 0x7c, 0xf5, 0xc0, 0x35, 0x72, 0x7e, 0xd3, 0x60, 0x6e,
	0x62, 0x8c, 0xbc, 0x1c, 0xc2, 0x60, 0x9f, 0xf1, 0x13, 0x26, 0x57, 0x10, 0x6c, 0x5c, 0x6e, 0x60,
	0xa6, 0xf3, 0xad, 0x21, 0x3d, 0xcb, 0x42, 0xa5, 0xb7, 0x12, 0x91, 0xda, 0x73, 0x42, 0x20, 0x50,
	0xec, 0x09, 0x6d, 0xe3, 0x80, 0xda, 0x3a, 0x99, 0x43, 0x7f, 0xc5, 0xe4, 0x67, 0xd6, 0x64, 0x0d,
	0xd1, 0x8a, 0xc9, 0x75, 0xad, 0xe5, 0xc5, 0xc4, 0xd4, 0x59, 0xe5, 0xd8, 0x98, 0xda, 0x9a, 0xcc,
	0x21, 0x74, 0xeb, 0xf2, 0xb7, 0x9a, 0xf8, 0xa1, 0xdd, 0x52, 0xa8, 0x17, 0x93, 0xff, 0x10, 0xb5,
	0xd7, 0x30, 0x31, 0xfa, 0xd2, 0xbc, 0xc6, 0x98, 0x9a, 0x7c, 0x83, 0x30, 0x17, 0x75, 0xc9, 0x1e,
	0x6c, 0xcc, 0x98, 0xfa, 0xaf, 0xa4, 0x82, 0xe1, 0xae, 0xd1, 0x4c, 0xd4, 0x8a, 0xfc, 0x86, 0xb8,
	0xc8, 0x74, 0x76, 0x10, 0x8d, 0x56, 0x7e, 0x5c, 0xbb, 0x21, 0xf3, 0x16, 0x9e, 0xa1, 0x91, 0x21,
	0x76, 0x8d, 0x56, 0xe4, 0x1f, 0x4c, 0x2a, 0xd4, 0xd9, 0x9b, 0xa3, 0xf7, 0xb1, 0x63, 0xdc, 0x52,
	0xc6, 0x95, 0xdc, 0x43, 0xb8, 0x17, 0xfc, 0x54, 0x21, 0xf9, 0x05, 0xe0, 0x46, 0x3f, 0x48, 0x2c,
	0xdf, 0xbf, 0xa9, 0x31, 0x53, 0x2c, 0x69, 0xec, 0x64, 0x8a, 0x25, 0x59, 0xc0, 0x50, 0xb8, 0x38,
	0xdf, 0xe5, 0x4b, 0xbb, 0x04, 0xdf, 0xa4, 0x95, 0x97, 0xd1, 0x5d, 0x58, 0x89, 0x02, 0xb9, 0x3a,
	0x86, 0xf6, 0xf7, 0xf9, 0xfb, 0x12, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x23, 0x79, 0xad, 0x6d, 0x02,
	0x00, 0x00,
}
