// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto.proto

package rwacryptocell

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EncAlgo int32

const (
	EncAlgo_UNKNOWN_EA        EncAlgo = 0
	EncAlgo_XCHACHA20POLY1305 EncAlgo = 1
)

var EncAlgo_name = map[int32]string{
	0: "UNKNOWN_EA",
	1: "XCHACHA20POLY1305",
}

var EncAlgo_value = map[string]int32{
	"UNKNOWN_EA":        0,
	"XCHACHA20POLY1305": 1,
}

func (x EncAlgo) String() string {
	return proto.EnumName(EncAlgo_name, int32(x))
}

func (EncAlgo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{0}
}

type HashFunc int32

const (
	HashFunc_UNKNOWN_HF HashFunc = 0
	// might as well use a number at least someone else is using
	// https://github.com/multiformats/multicodec/blob/master/table.csv
	HashFunc_SHA256   HashFunc = 18
	HashFunc_SHA3_256 HashFunc = 22
)

var HashFunc_name = map[int32]string{
	0:  "UNKNOWN_HF",
	18: "SHA256",
	22: "SHA3_256",
}

var HashFunc_value = map[string]int32{
	"UNKNOWN_HF": 0,
	"SHA256":     18,
	"SHA3_256":   22,
}

func (x HashFunc) String() string {
	return proto.EnumName(HashFunc_name, int32(x))
}

func (HashFunc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{1}
}

type SigAlgo int32

const (
	SigAlgo_UNKNOWN_SA SigAlgo = 0
	SigAlgo_ED25519    SigAlgo = 1
)

var SigAlgo_name = map[int32]string{
	0: "UNKNOWN_SA",
	1: "ED25519",
}

var SigAlgo_value = map[string]int32{
	"UNKNOWN_SA": 0,
	"ED25519":    1,
}

func (x SigAlgo) String() string {
	return proto.EnumName(SigAlgo_name, int32(x))
}

func (SigAlgo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{2}
}

type AsymEncAlgo int32

const (
	AsymEncAlgo_UNKNOWN_AEA        AsymEncAlgo = 0
	AsymEncAlgo_CURVE25519_NACLBOX AsymEncAlgo = 1
)

var AsymEncAlgo_name = map[int32]string{
	0: "UNKNOWN_AEA",
	1: "CURVE25519_NACLBOX",
}

var AsymEncAlgo_value = map[string]int32{
	"UNKNOWN_AEA":        0,
	"CURVE25519_NACLBOX": 1,
}

func (x AsymEncAlgo) String() string {
	return proto.EnumName(AsymEncAlgo_name, int32(x))
}

func (AsymEncAlgo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{3}
}

type EncMsg struct {
	Algo                 EncAlgo  `protobuf:"varint,1,opt,name=algo,proto3,enum=ccp.EncAlgo" json:"algo,omitempty"`
	Ctext                []byte   `protobuf:"bytes,2,opt,name=ctext,proto3" json:"ctext,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncMsg) Reset()         { *m = EncMsg{} }
func (m *EncMsg) String() string { return proto.CompactTextString(m) }
func (*EncMsg) ProtoMessage()    {}
func (*EncMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{0}
}

func (m *EncMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncMsg.Unmarshal(m, b)
}
func (m *EncMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncMsg.Marshal(b, m, deterministic)
}
func (m *EncMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncMsg.Merge(m, src)
}
func (m *EncMsg) XXX_Size() int {
	return xxx_messageInfo_EncMsg.Size(m)
}
func (m *EncMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EncMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EncMsg proto.InternalMessageInfo

func (m *EncMsg) GetAlgo() EncAlgo {
	if m != nil {
		return m.Algo
	}
	return EncAlgo_UNKNOWN_EA
}

func (m *EncMsg) GetCtext() []byte {
	if m != nil {
		return m.Ctext
	}
	return nil
}

func (m *EncMsg) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type Sig struct {
	HashFunc             HashFunc `protobuf:"varint,1,opt,name=hash_func,json=hashFunc,proto3,enum=ccp.HashFunc" json:"hash_func,omitempty"`
	Algo                 SigAlgo  `protobuf:"varint,2,opt,name=algo,proto3,enum=ccp.SigAlgo" json:"algo,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sig) Reset()         { *m = Sig{} }
func (m *Sig) String() string { return proto.CompactTextString(m) }
func (*Sig) ProtoMessage()    {}
func (*Sig) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{1}
}

func (m *Sig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sig.Unmarshal(m, b)
}
func (m *Sig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sig.Marshal(b, m, deterministic)
}
func (m *Sig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sig.Merge(m, src)
}
func (m *Sig) XXX_Size() int {
	return xxx_messageInfo_Sig.Size(m)
}
func (m *Sig) XXX_DiscardUnknown() {
	xxx_messageInfo_Sig.DiscardUnknown(m)
}

var xxx_messageInfo_Sig proto.InternalMessageInfo

func (m *Sig) GetHashFunc() HashFunc {
	if m != nil {
		return m.HashFunc
	}
	return HashFunc_UNKNOWN_HF
}

func (m *Sig) GetAlgo() SigAlgo {
	if m != nil {
		return m.Algo
	}
	return SigAlgo_UNKNOWN_SA
}

func (m *Sig) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type AsymEncMsg struct {
	Algo                 AsymEncAlgo `protobuf:"varint,1,opt,name=algo,proto3,enum=ccp.AsymEncAlgo" json:"algo,omitempty"`
	SenderKey            *Key        `protobuf:"bytes,2,opt,name=sender_key,json=senderKey,proto3" json:"sender_key,omitempty"`
	Ctext                []byte      `protobuf:"bytes,3,opt,name=ctext,proto3" json:"ctext,omitempty"`
	Nonce                []byte      `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AsymEncMsg) Reset()         { *m = AsymEncMsg{} }
func (m *AsymEncMsg) String() string { return proto.CompactTextString(m) }
func (*AsymEncMsg) ProtoMessage()    {}
func (*AsymEncMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{2}
}

func (m *AsymEncMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsymEncMsg.Unmarshal(m, b)
}
func (m *AsymEncMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsymEncMsg.Marshal(b, m, deterministic)
}
func (m *AsymEncMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsymEncMsg.Merge(m, src)
}
func (m *AsymEncMsg) XXX_Size() int {
	return xxx_messageInfo_AsymEncMsg.Size(m)
}
func (m *AsymEncMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AsymEncMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AsymEncMsg proto.InternalMessageInfo

func (m *AsymEncMsg) GetAlgo() AsymEncAlgo {
	if m != nil {
		return m.Algo
	}
	return AsymEncAlgo_UNKNOWN_AEA
}

func (m *AsymEncMsg) GetSenderKey() *Key {
	if m != nil {
		return m.SenderKey
	}
	return nil
}

func (m *AsymEncMsg) GetCtext() []byte {
	if m != nil {
		return m.Ctext
	}
	return nil
}

func (m *AsymEncMsg) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type Entity struct {
	SigningKey           *Key     `protobuf:"bytes,1,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	EncryptionKey        *Key     `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{3}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetSigningKey() *Key {
	if m != nil {
		return m.SigningKey
	}
	return nil
}

func (m *Entity) GetEncryptionKey() *Key {
	if m != nil {
		return m.EncryptionKey
	}
	return nil
}

type Key struct {
	// Types that are valid to be assigned to Key:
	//	*Key_Ed25519_Private
	//	*Key_Ed25519
	//	*Key_Curve25519_Private
	//	*Key_Curve25519
	Key                  isKey_Key `protobuf_oneof:"key"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{4}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

type isKey_Key interface {
	isKey_Key()
}

type Key_Ed25519_Private struct {
	Ed25519_Private []byte `protobuf:"bytes,1,opt,name=Ed25519_Private,json=Ed25519Private,proto3,oneof"`
}

type Key_Ed25519 struct {
	Ed25519 []byte `protobuf:"bytes,2,opt,name=Ed25519,proto3,oneof"`
}

type Key_Curve25519_Private struct {
	Curve25519_Private []byte `protobuf:"bytes,3,opt,name=Curve25519_Private,json=Curve25519Private,proto3,oneof"`
}

type Key_Curve25519 struct {
	Curve25519 []byte `protobuf:"bytes,4,opt,name=Curve25519,proto3,oneof"`
}

func (*Key_Ed25519_Private) isKey_Key() {}

func (*Key_Ed25519) isKey_Key() {}

func (*Key_Curve25519_Private) isKey_Key() {}

func (*Key_Curve25519) isKey_Key() {}

func (m *Key) GetKey() isKey_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Key) GetEd25519_Private() []byte {
	if x, ok := m.GetKey().(*Key_Ed25519_Private); ok {
		return x.Ed25519_Private
	}
	return nil
}

func (m *Key) GetEd25519() []byte {
	if x, ok := m.GetKey().(*Key_Ed25519); ok {
		return x.Ed25519
	}
	return nil
}

func (m *Key) GetCurve25519_Private() []byte {
	if x, ok := m.GetKey().(*Key_Curve25519_Private); ok {
		return x.Curve25519_Private
	}
	return nil
}

func (m *Key) GetCurve25519() []byte {
	if x, ok := m.GetKey().(*Key_Curve25519); ok {
		return x.Curve25519
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Key) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Key_Ed25519_Private)(nil),
		(*Key_Ed25519)(nil),
		(*Key_Curve25519_Private)(nil),
		(*Key_Curve25519)(nil),
	}
}

func init() {
	proto.RegisterEnum("ccp.EncAlgo", EncAlgo_name, EncAlgo_value)
	proto.RegisterEnum("ccp.HashFunc", HashFunc_name, HashFunc_value)
	proto.RegisterEnum("ccp.SigAlgo", SigAlgo_name, SigAlgo_value)
	proto.RegisterEnum("ccp.AsymEncAlgo", AsymEncAlgo_name, AsymEncAlgo_value)
	proto.RegisterType((*EncMsg)(nil), "ccp.EncMsg")
	proto.RegisterType((*Sig)(nil), "ccp.Sig")
	proto.RegisterType((*AsymEncMsg)(nil), "ccp.AsymEncMsg")
	proto.RegisterType((*Entity)(nil), "ccp.Entity")
	proto.RegisterType((*Key)(nil), "ccp.Key")
}

func init() { proto.RegisterFile("crypto.proto", fileDescriptor_527278fb02d03321) }

var fileDescriptor_527278fb02d03321 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0x25, 0x4d, 0x0b, 0xf4, 0x42, 0x69, 0x6a, 0x7d, 0x5f, 0x85, 0xf6, 0x84, 0xd0, 0xb4, 0xb5,
	0x3c, 0x10, 0x0a, 0xa3, 0x53, 0x1f, 0x03, 0x4b, 0x15, 0x89, 0x0e, 0xaa, 0x44, 0xed, 0xba, 0xbd,
	0x44, 0xc1, 0xb8, 0x4e, 0x44, 0x6a, 0x47, 0x49, 0x68, 0x97, 0x5f, 0xb0, 0x7f, 0xb2, 0xdf, 0x39,
	0xc5, 0x31, 0x23, 0x9d, 0xfa, 0xe6, 0x7b, 0x8e, 0xef, 0xb9, 0xe7, 0x5e, 0x5f, 0x43, 0x13, 0xc7,
	0x59, 0x94, 0xf2, 0x7e, 0x14, 0xf3, 0x94, 0x23, 0x15, 0xe3, 0xa8, 0x7b, 0x0f, 0x55, 0x93, 0xe1,
	0xaf, 0x09, 0x45, 0x1d, 0xd8, 0xf7, 0x42, 0xca, 0xdb, 0x4a, 0x47, 0x39, 0x6b, 0x0d, 0x9b, 0x7d,
	0x8c, 0xa3, 0xbe, 0xc9, 0xb0, 0x11, 0x52, 0x6e, 0x0b, 0x06, 0xfd, 0x07, 0x07, 0x38, 0x25, 0x3f,
	0xd3, 0xf6, 0x5e, 0x47, 0x39, 0x6b, 0xda, 0x45, 0x90, 0xa3, 0x8c, 0x33, 0x4c, 0xda, 0x6a, 0x81,
	0x8a, 0xa0, 0x4b, 0x40, 0x75, 0x02, 0x8a, 0x7a, 0x70, 0xe8, 0x7b, 0x89, 0xef, 0x3e, 0x6e, 0x18,
	0x96, 0xca, 0x47, 0x42, 0xd9, 0xf2, 0x12, 0xff, 0x7a, 0xc3, 0xb0, 0x5d, 0xf7, 0xe5, 0xe9, 0xaf,
	0x81, 0xbd, 0x92, 0x01, 0x27, 0xa0, 0x25, 0x03, 0x1a, 0xa8, 0x49, 0x40, 0x65, 0xa1, 0xfc, 0xd8,
	0xfd, 0xa5, 0x00, 0x18, 0x49, 0xf6, 0x24, 0x7b, 0x78, 0xff, 0xaa, 0x07, 0x4d, 0x48, 0x48, 0xba,
	0x24, 0xf3, 0x11, 0x20, 0x21, 0x6c, 0x45, 0x62, 0x77, 0x4d, 0x32, 0x51, 0xae, 0x31, 0xac, 0x8b,
	0xbb, 0x33, 0x92, 0xd9, 0x87, 0x05, 0x37, 0x23, 0xd9, 0xae, 0x61, 0xf5, 0xcd, 0x86, 0xf7, 0xcb,
	0x0d, 0xaf, 0xf2, 0x41, 0xa6, 0x41, 0x9a, 0xa1, 0x73, 0x68, 0x24, 0x01, 0x65, 0x01, 0xa3, 0x42,
	0x5f, 0xf9, 0x47, 0x1f, 0x24, 0x99, 0x17, 0xd0, 0xa1, 0x45, 0x98, 0x78, 0x94, 0x80, 0xb3, 0x37,
	0xdd, 0x1c, 0xed, 0xf8, 0x19, 0xc9, 0xba, 0xbf, 0x15, 0x50, 0xf3, 0xc4, 0x73, 0x38, 0x36, 0x57,
	0xc3, 0xf1, 0xf8, 0xe2, 0xca, 0xbd, 0x8d, 0x83, 0x67, 0x2f, 0x25, 0xa2, 0x4e, 0xd3, 0xaa, 0xd8,
	0x2d, 0x49, 0x48, 0x1c, 0xbd, 0x83, 0x9a, 0x44, 0x8a, 0x77, 0xb3, 0x2a, 0xf6, 0x16, 0x40, 0x3a,
	0xa0, 0xe9, 0x26, 0x7e, 0x26, 0xaf, 0x95, 0x54, 0x79, 0xed, 0x64, 0xc7, 0x6d, 0xc5, 0x3a, 0x00,
	0x3b, 0xb0, 0x18, 0x80, 0x55, 0xb1, 0x4b, 0xd8, 0xe4, 0x00, 0xd4, 0x35, 0xc9, 0x7a, 0x03, 0xa8,
	0xc9, 0xa1, 0xa3, 0x16, 0xc0, 0xdd, 0x7c, 0x36, 0x5f, 0x7c, 0x9b, 0xbb, 0xa6, 0xa1, 0x55, 0xd0,
	0xff, 0x70, 0xf2, 0x30, 0xb5, 0x8c, 0xa9, 0x65, 0x0c, 0x07, 0xb7, 0x8b, 0x9b, 0xef, 0x17, 0xa3,
	0xc1, 0x58, 0x53, 0x7a, 0x9f, 0xa0, 0xbe, 0x5d, 0x8a, 0x72, 0x8a, 0x75, 0xad, 0x55, 0x10, 0x40,
	0xd5, 0xb1, 0x8c, 0xe1, 0xf8, 0x52, 0x43, 0xa8, 0x09, 0x75, 0xc7, 0x32, 0x46, 0x6e, 0x1e, 0x9d,
	0xf6, 0x3e, 0x40, 0x4d, 0xee, 0x48, 0x39, 0xc9, 0xc9, 0xeb, 0x34, 0xa0, 0x66, 0x7e, 0x11, 0xa6,
	0x34, 0xa5, 0x77, 0x09, 0x8d, 0xd2, 0x22, 0xa0, 0x63, 0x68, 0x6c, 0xef, 0x1a, 0xc2, 0xd4, 0x29,
	0xa0, 0xe9, 0x9d, 0x7d, 0x6f, 0x16, 0x93, 0x98, 0x1b, 0xd3, 0x9b, 0xc9, 0xe2, 0x41, 0x53, 0x26,
	0x57, 0x3f, 0x3e, 0xd3, 0x20, 0xf5, 0x37, 0xcb, 0x3e, 0xe6, 0x4f, 0xfa, 0x32, 0x26, 0x6c, 0xc5,
	0x19, 0xf6, 0xe2, 0x98, 0x87, 0xa1, 0xfe, 0x42, 0x96, 0x8f, 0x89, 0x1e, 0xad, 0xa9, 0x8e, 0x49,
	0x18, 0x26, 0x7a, 0xfc, 0xe2, 0x15, 0x3f, 0x2c, 0x0f, 0x97, 0x55, 0xf1, 0xcd, 0x46, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xba, 0x15, 0xa2, 0x9c, 0x76, 0x03, 0x00, 0x00,
}
