// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cellspecs.proto

package webfsim

import (
	fmt "fmt"
	rwacryptocell "github.com/brendoncarroll/webfs/pkg/cells/rwacryptocell"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CellSpec struct {
	// Types that are valid to be assigned to Spec:
	//	*CellSpec_Http
	//	*CellSpec_Crypto
	Spec                 isCellSpec_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CellSpec) Reset()         { *m = CellSpec{} }
func (m *CellSpec) String() string { return proto.CompactTextString(m) }
func (*CellSpec) ProtoMessage()    {}
func (*CellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{0}
}

func (m *CellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellSpec.Unmarshal(m, b)
}
func (m *CellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellSpec.Marshal(b, m, deterministic)
}
func (m *CellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellSpec.Merge(m, src)
}
func (m *CellSpec) XXX_Size() int {
	return xxx_messageInfo_CellSpec.Size(m)
}
func (m *CellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CellSpec proto.InternalMessageInfo

type isCellSpec_Spec interface {
	isCellSpec_Spec()
}

type CellSpec_Http struct {
	Http *HTTPCellSpec `protobuf:"bytes,1,opt,name=http,proto3,oneof"`
}

type CellSpec_Crypto struct {
	Crypto *CryptoCellSpec `protobuf:"bytes,128,opt,name=crypto,proto3,oneof"`
}

func (*CellSpec_Http) isCellSpec_Spec() {}

func (*CellSpec_Crypto) isCellSpec_Spec() {}

func (m *CellSpec) GetSpec() isCellSpec_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *CellSpec) GetHttp() *HTTPCellSpec {
	if x, ok := m.GetSpec().(*CellSpec_Http); ok {
		return x.Http
	}
	return nil
}

func (m *CellSpec) GetCrypto() *CryptoCellSpec {
	if x, ok := m.GetSpec().(*CellSpec_Crypto); ok {
		return x.Crypto
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CellSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CellSpec_Http)(nil),
		(*CellSpec_Crypto)(nil),
	}
}

type HTTPCellSpec struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AuthHeader           string   `protobuf:"bytes,2,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPCellSpec) Reset()         { *m = HTTPCellSpec{} }
func (m *HTTPCellSpec) String() string { return proto.CompactTextString(m) }
func (*HTTPCellSpec) ProtoMessage()    {}
func (*HTTPCellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{1}
}

func (m *HTTPCellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPCellSpec.Unmarshal(m, b)
}
func (m *HTTPCellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPCellSpec.Marshal(b, m, deterministic)
}
func (m *HTTPCellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPCellSpec.Merge(m, src)
}
func (m *HTTPCellSpec) XXX_Size() int {
	return xxx_messageInfo_HTTPCellSpec.Size(m)
}
func (m *HTTPCellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPCellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPCellSpec proto.InternalMessageInfo

func (m *HTTPCellSpec) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPCellSpec) GetAuthHeader() string {
	if m != nil {
		return m.AuthHeader
	}
	return ""
}

type CryptoCellSpec struct {
	Inner                *CellSpec             `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	PrivateEntity        *rwacryptocell.Entity `protobuf:"bytes,2,opt,name=private_entity,json=privateEntity,proto3" json:"private_entity,omitempty"`
	PublicEntity         *rwacryptocell.Entity `protobuf:"bytes,3,opt,name=public_entity,json=publicEntity,proto3" json:"public_entity,omitempty"`
	Who                  *rwacryptocell.Who    `protobuf:"bytes,4,opt,name=who,proto3" json:"who,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CryptoCellSpec) Reset()         { *m = CryptoCellSpec{} }
func (m *CryptoCellSpec) String() string { return proto.CompactTextString(m) }
func (*CryptoCellSpec) ProtoMessage()    {}
func (*CryptoCellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{2}
}

func (m *CryptoCellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoCellSpec.Unmarshal(m, b)
}
func (m *CryptoCellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoCellSpec.Marshal(b, m, deterministic)
}
func (m *CryptoCellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoCellSpec.Merge(m, src)
}
func (m *CryptoCellSpec) XXX_Size() int {
	return xxx_messageInfo_CryptoCellSpec.Size(m)
}
func (m *CryptoCellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoCellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoCellSpec proto.InternalMessageInfo

func (m *CryptoCellSpec) GetInner() *CellSpec {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *CryptoCellSpec) GetPrivateEntity() *rwacryptocell.Entity {
	if m != nil {
		return m.PrivateEntity
	}
	return nil
}

func (m *CryptoCellSpec) GetPublicEntity() *rwacryptocell.Entity {
	if m != nil {
		return m.PublicEntity
	}
	return nil
}

func (m *CryptoCellSpec) GetWho() *rwacryptocell.Who {
	if m != nil {
		return m.Who
	}
	return nil
}

func init() {
	proto.RegisterType((*CellSpec)(nil), "webfs.CellSpec")
	proto.RegisterType((*HTTPCellSpec)(nil), "webfs.HTTPCellSpec")
	proto.RegisterType((*CryptoCellSpec)(nil), "webfs.CryptoCellSpec")
}

func init() { proto.RegisterFile("cellspecs.proto", fileDescriptor_439b9c02290cbc21) }

var fileDescriptor_439b9c02290cbc21 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x51, 0x4b, 0xbc, 0x40,
	0x14, 0xc5, 0xff, 0xfe, 0x75, 0x6d, 0xbd, 0xba, 0xbb, 0x31, 0x11, 0x88, 0x2f, 0x85, 0x10, 0xd4,
	0x8b, 0x2c, 0xf6, 0x09, 0xda, 0x25, 0xf0, 0x31, 0x6c, 0x21, 0xe8, 0x65, 0xd1, 0x69, 0x42, 0x61,
	0x72, 0x86, 0x71, 0x6c, 0xd9, 0xb7, 0xbe, 0x56, 0xdf, 0x2e, 0xbc, 0x33, 0xc2, 0x46, 0x6f, 0xd7,
	0x73, 0x7f, 0xe7, 0xdc, 0x83, 0x03, 0x2b, 0xca, 0x38, 0xef, 0x25, 0xa3, 0x7d, 0x26, 0x95, 0xd0,
	0x82, 0xcc, 0x0e, 0xac, 0x7e, 0xef, 0x93, 0x88, 0xaa, 0xa3, 0xd4, 0xc2, 0x88, 0x49, 0x40, 0xa9,
	0x34, 0x63, 0x2a, 0x60, 0xbe, 0x65, 0x9c, 0x3f, 0x4b, 0x46, 0xc9, 0x1d, 0x78, 0x8d, 0xd6, 0x32,
	0x76, 0xae, 0x9d, 0xdb, 0x30, 0xbf, 0xc8, 0xd0, 0x9a, 0x15, 0xbb, 0xdd, 0xd3, 0x84, 0x14, 0xff,
	0x4a, 0x44, 0xc8, 0x1a, 0x7c, 0x93, 0x18, 0x7f, 0x19, 0xfa, 0xd2, 0xd2, 0x5b, 0x54, 0x4f, 0x78,
	0xcb, 0x6d, 0x7c, 0xf0, 0xc6, 0x5e, 0xe9, 0x03, 0x44, 0xa7, 0x89, 0xe4, 0x1c, 0xdc, 0x41, 0x71,
	0xbc, 0x19, 0x94, 0xe3, 0x48, 0xae, 0x20, 0xac, 0x06, 0xdd, 0xec, 0x1b, 0x56, 0xbd, 0x31, 0x15,
	0xff, 0xc7, 0x0d, 0x8c, 0x52, 0x81, 0x4a, 0xfa, 0xed, 0xc0, 0xf2, 0xf7, 0x1d, 0x72, 0x03, 0xb3,
	0xb6, 0xeb, 0x98, 0xb2, 0xdd, 0x57, 0x53, 0x1b, 0xbb, 0x2f, 0xcd, 0x96, 0xe4, 0xb0, 0x94, 0xaa,
	0xfd, 0xac, 0x34, 0xdb, 0xb3, 0x4e, 0xb7, 0xfa, 0x88, 0xe9, 0x61, 0x1e, 0x66, 0xe3, 0x1f, 0x79,
	0x44, 0xa9, 0x5c, 0x58, 0xc4, 0x7c, 0x92, 0x35, 0x2c, 0xe4, 0x50, 0xf3, 0x96, 0x4e, 0x16, 0xf7,
	0xaf, 0x25, 0x32, 0x84, 0x75, 0x24, 0xe0, 0x1e, 0x1a, 0x11, 0x7b, 0xc8, 0xcd, 0x91, 0x7b, 0x69,
	0x44, 0x39, 0x8a, 0x9b, 0xe0, 0xf5, 0x0c, 0xab, 0xb5, 0x1f, 0xb5, 0x8f, 0x2f, 0x70, 0xff, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0x5d, 0x77, 0xe5, 0xb4, 0x01, 0x00, 0x00,
}
