// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cellspecs.proto

package webfsim

import (
	fmt "fmt"
	rwacryptocell "github.com/brendoncarroll/webfs/pkg/cells/rwacryptocell"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CellSpec struct {
	// Types that are valid to be assigned to Spec:
	//	*CellSpec_Http
	//	*CellSpec_Rwacrypto
	//	*CellSpec_Secretbox
	Spec                 isCellSpec_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CellSpec) Reset()         { *m = CellSpec{} }
func (m *CellSpec) String() string { return proto.CompactTextString(m) }
func (*CellSpec) ProtoMessage()    {}
func (*CellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{0}
}

func (m *CellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellSpec.Unmarshal(m, b)
}
func (m *CellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellSpec.Marshal(b, m, deterministic)
}
func (m *CellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellSpec.Merge(m, src)
}
func (m *CellSpec) XXX_Size() int {
	return xxx_messageInfo_CellSpec.Size(m)
}
func (m *CellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CellSpec proto.InternalMessageInfo

type isCellSpec_Spec interface {
	isCellSpec_Spec()
}

type CellSpec_Http struct {
	Http *HTTPCellSpec `protobuf:"bytes,1,opt,name=http,proto3,oneof"`
}

type CellSpec_Rwacrypto struct {
	Rwacrypto *RWACryptoCellSpec `protobuf:"bytes,128,opt,name=rwacrypto,proto3,oneof"`
}

type CellSpec_Secretbox struct {
	Secretbox *SecretBoxCellSpec `protobuf:"bytes,129,opt,name=secretbox,proto3,oneof"`
}

func (*CellSpec_Http) isCellSpec_Spec() {}

func (*CellSpec_Rwacrypto) isCellSpec_Spec() {}

func (*CellSpec_Secretbox) isCellSpec_Spec() {}

func (m *CellSpec) GetSpec() isCellSpec_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *CellSpec) GetHttp() *HTTPCellSpec {
	if x, ok := m.GetSpec().(*CellSpec_Http); ok {
		return x.Http
	}
	return nil
}

func (m *CellSpec) GetRwacrypto() *RWACryptoCellSpec {
	if x, ok := m.GetSpec().(*CellSpec_Rwacrypto); ok {
		return x.Rwacrypto
	}
	return nil
}

func (m *CellSpec) GetSecretbox() *SecretBoxCellSpec {
	if x, ok := m.GetSpec().(*CellSpec_Secretbox); ok {
		return x.Secretbox
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CellSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CellSpec_Http)(nil),
		(*CellSpec_Rwacrypto)(nil),
		(*CellSpec_Secretbox)(nil),
	}
}

type HTTPCellSpec struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AuthHeader           string   `protobuf:"bytes,2,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPCellSpec) Reset()         { *m = HTTPCellSpec{} }
func (m *HTTPCellSpec) String() string { return proto.CompactTextString(m) }
func (*HTTPCellSpec) ProtoMessage()    {}
func (*HTTPCellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{1}
}

func (m *HTTPCellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPCellSpec.Unmarshal(m, b)
}
func (m *HTTPCellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPCellSpec.Marshal(b, m, deterministic)
}
func (m *HTTPCellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPCellSpec.Merge(m, src)
}
func (m *HTTPCellSpec) XXX_Size() int {
	return xxx_messageInfo_HTTPCellSpec.Size(m)
}
func (m *HTTPCellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPCellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPCellSpec proto.InternalMessageInfo

func (m *HTTPCellSpec) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPCellSpec) GetAuthHeader() string {
	if m != nil {
		return m.AuthHeader
	}
	return ""
}

type RWACryptoCellSpec struct {
	Inner                *CellSpec             `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	PrivateEntity        *rwacryptocell.Entity `protobuf:"bytes,2,opt,name=private_entity,json=privateEntity,proto3" json:"private_entity,omitempty"`
	PublicEntity         *rwacryptocell.Entity `protobuf:"bytes,3,opt,name=public_entity,json=publicEntity,proto3" json:"public_entity,omitempty"`
	Who                  *rwacryptocell.Who    `protobuf:"bytes,4,opt,name=who,proto3" json:"who,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RWACryptoCellSpec) Reset()         { *m = RWACryptoCellSpec{} }
func (m *RWACryptoCellSpec) String() string { return proto.CompactTextString(m) }
func (*RWACryptoCellSpec) ProtoMessage()    {}
func (*RWACryptoCellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{2}
}

func (m *RWACryptoCellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWACryptoCellSpec.Unmarshal(m, b)
}
func (m *RWACryptoCellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWACryptoCellSpec.Marshal(b, m, deterministic)
}
func (m *RWACryptoCellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWACryptoCellSpec.Merge(m, src)
}
func (m *RWACryptoCellSpec) XXX_Size() int {
	return xxx_messageInfo_RWACryptoCellSpec.Size(m)
}
func (m *RWACryptoCellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_RWACryptoCellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_RWACryptoCellSpec proto.InternalMessageInfo

func (m *RWACryptoCellSpec) GetInner() *CellSpec {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *RWACryptoCellSpec) GetPrivateEntity() *rwacryptocell.Entity {
	if m != nil {
		return m.PrivateEntity
	}
	return nil
}

func (m *RWACryptoCellSpec) GetPublicEntity() *rwacryptocell.Entity {
	if m != nil {
		return m.PublicEntity
	}
	return nil
}

func (m *RWACryptoCellSpec) GetWho() *rwacryptocell.Who {
	if m != nil {
		return m.Who
	}
	return nil
}

type SecretBoxCellSpec struct {
	Inner                *CellSpec `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	Secret               []byte    `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SecretBoxCellSpec) Reset()         { *m = SecretBoxCellSpec{} }
func (m *SecretBoxCellSpec) String() string { return proto.CompactTextString(m) }
func (*SecretBoxCellSpec) ProtoMessage()    {}
func (*SecretBoxCellSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_439b9c02290cbc21, []int{3}
}

func (m *SecretBoxCellSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretBoxCellSpec.Unmarshal(m, b)
}
func (m *SecretBoxCellSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretBoxCellSpec.Marshal(b, m, deterministic)
}
func (m *SecretBoxCellSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretBoxCellSpec.Merge(m, src)
}
func (m *SecretBoxCellSpec) XXX_Size() int {
	return xxx_messageInfo_SecretBoxCellSpec.Size(m)
}
func (m *SecretBoxCellSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretBoxCellSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SecretBoxCellSpec proto.InternalMessageInfo

func (m *SecretBoxCellSpec) GetInner() *CellSpec {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *SecretBoxCellSpec) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func init() {
	proto.RegisterType((*CellSpec)(nil), "webfs.CellSpec")
	proto.RegisterType((*HTTPCellSpec)(nil), "webfs.HTTPCellSpec")
	proto.RegisterType((*RWACryptoCellSpec)(nil), "webfs.RWACryptoCellSpec")
	proto.RegisterType((*SecretBoxCellSpec)(nil), "webfs.SecretBoxCellSpec")
}

func init() { proto.RegisterFile("cellspecs.proto", fileDescriptor_439b9c02290cbc21) }

var fileDescriptor_439b9c02290cbc21 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x18, 0xc4, 0xdf, 0xbc, 0xfd, 0x63, 0xf3, 0x24, 0xb5, 0x76, 0x05, 0x09, 0xbd, 0x28, 0x01, 0x41,
	0x2f, 0x41, 0xea, 0xc9, 0x63, 0x5b, 0x84, 0x1e, 0x65, 0x5b, 0x28, 0x78, 0x29, 0xc9, 0xfa, 0x48,
	0x02, 0xb1, 0xbb, 0x6c, 0xb6, 0xb6, 0xbd, 0xe9, 0x67, 0xf2, 0xea, 0x87, 0x93, 0x3c, 0x9b, 0x6a,
	0x25, 0x17, 0x6f, 0xbb, 0x33, 0xf3, 0x4b, 0x26, 0x43, 0xa0, 0x27, 0x30, 0xcf, 0x0b, 0x85, 0xa2,
	0x88, 0x94, 0x96, 0x46, 0xb2, 0xd6, 0x06, 0x93, 0xe7, 0x62, 0xe0, 0x0b, 0xbd, 0x53, 0x46, 0x5a,
	0x71, 0xe0, 0x0a, 0xa1, 0xec, 0x31, 0xfc, 0x70, 0xa0, 0x33, 0xc1, 0x3c, 0x9f, 0x29, 0x14, 0xec,
	0x1a, 0x9a, 0xa9, 0x31, 0x2a, 0x70, 0x2e, 0x9c, 0x2b, 0x6f, 0x78, 0x1a, 0x11, 0x1b, 0x4d, 0xe7,
	0xf3, 0x87, 0x7d, 0x64, 0xfa, 0x8f, 0x53, 0x84, 0xdd, 0x81, 0xab, 0x37, 0xb1, 0x7d, 0x6a, 0xf0,
	0x66, 0x81, 0xa0, 0x02, 0xf8, 0x62, 0x34, 0x21, 0xe3, 0x80, 0xfa, 0x49, 0x97, 0x68, 0x81, 0x42,
	0xa3, 0x49, 0xe4, 0x36, 0x78, 0xff, 0x8d, 0xce, 0xc8, 0x18, 0xcb, 0xed, 0x21, 0xfa, 0x9d, 0x1e,
	0xb7, 0xa1, 0x59, 0x7e, 0x5c, 0x38, 0x02, 0xff, 0xb0, 0x15, 0x3b, 0x81, 0xc6, 0x5a, 0xe7, 0xd4,
	0xdb, 0xe5, 0xe5, 0x91, 0x9d, 0x83, 0x17, 0xaf, 0x4d, 0xba, 0x4c, 0x31, 0x7e, 0x42, 0x1d, 0xfc,
	0x27, 0x07, 0x4a, 0x69, 0x4a, 0x4a, 0xf8, 0xe9, 0x40, 0xbf, 0x56, 0x94, 0x5d, 0x42, 0x2b, 0x5b,
	0xad, 0x50, 0x57, 0x13, 0xf4, 0xaa, 0x5a, 0x7b, 0x9f, 0x5b, 0x97, 0x0d, 0xe1, 0x58, 0xe9, 0xec,
	0x35, 0x36, 0xb8, 0xc4, 0x95, 0xc9, 0xcc, 0x8e, 0x5e, 0xe0, 0x0d, 0xbd, 0xa8, 0x5c, 0xf6, 0x9e,
	0x24, 0xde, 0xad, 0x22, 0xf6, 0xca, 0x6e, 0xa0, 0xab, 0xd6, 0x49, 0x9e, 0x89, 0x3d, 0xd2, 0xa8,
	0x23, 0xbe, 0x4d, 0x54, 0xc4, 0x00, 0x1a, 0x9b, 0x54, 0x06, 0x4d, 0xca, 0x75, 0x28, 0xb7, 0x48,
	0x25, 0x2f, 0xc5, 0x90, 0x43, 0xbf, 0xb6, 0xd5, 0x5f, 0xdb, 0x9f, 0x41, 0xdb, 0x4e, 0x4a, 0xad,
	0x7d, 0x5e, 0xdd, 0xc6, 0xee, 0xe3, 0x11, 0x01, 0xd9, 0x4b, 0xd2, 0xa6, 0xbf, 0xe3, 0xf6, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x85, 0xe5, 0x27, 0x50, 0x02, 0x00, 0x00,
}
