// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects.proto

package webfsim

import (
	fmt "fmt"
	webref "github.com/brendoncarroll/webfs/pkg/webref"
	wrds "github.com/brendoncarroll/webfs/pkg/wrds"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Object struct {
	// Types that are valid to be assigned to Value:
	//	*Object_File
	//	*Object_Dir
	//	*Object_Volume
	Value                isObject_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{0}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

type isObject_Value interface {
	isObject_Value()
}

type Object_File struct {
	File *File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type Object_Dir struct {
	Dir *Dir `protobuf:"bytes,2,opt,name=dir,proto3,oneof"`
}

type Object_Volume struct {
	Volume *VolumeSpec `protobuf:"bytes,3,opt,name=volume,proto3,oneof"`
}

func (*Object_File) isObject_Value() {}

func (*Object_Dir) isObject_Value() {}

func (*Object_Volume) isObject_Value() {}

func (m *Object) GetValue() isObject_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Object) GetFile() *File {
	if x, ok := m.GetValue().(*Object_File); ok {
		return x.File
	}
	return nil
}

func (m *Object) GetDir() *Dir {
	if x, ok := m.GetValue().(*Object_Dir); ok {
		return x.Dir
	}
	return nil
}

func (m *Object) GetVolume() *VolumeSpec {
	if x, ok := m.GetValue().(*Object_Volume); ok {
		return x.Volume
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Object) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Object_File)(nil),
		(*Object_Dir)(nil),
		(*Object_Volume)(nil),
	}
}

type File struct {
	Tree                 *wrds.Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	Size                 uint64     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetTree() *wrds.Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Dir struct {
	Tree                 *wrds.Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}
func (*Dir) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{2}
}

func (m *Dir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dir.Unmarshal(m, b)
}
func (m *Dir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dir.Marshal(b, m, deterministic)
}
func (m *Dir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dir.Merge(m, src)
}
func (m *Dir) XXX_Size() int {
	return xxx_messageInfo_Dir.Size(m)
}
func (m *Dir) XXX_DiscardUnknown() {
	xxx_messageInfo_Dir.DiscardUnknown(m)
}

var xxx_messageInfo_Dir proto.InternalMessageInfo

func (m *Dir) GetTree() *wrds.Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

type DirEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Object               *Object  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirEntry) Reset()         { *m = DirEntry{} }
func (m *DirEntry) String() string { return proto.CompactTextString(m) }
func (*DirEntry) ProtoMessage()    {}
func (*DirEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{3}
}

func (m *DirEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirEntry.Unmarshal(m, b)
}
func (m *DirEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirEntry.Marshal(b, m, deterministic)
}
func (m *DirEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirEntry.Merge(m, src)
}
func (m *DirEntry) XXX_Size() int {
	return xxx_messageInfo_DirEntry.Size(m)
}
func (m *DirEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DirEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DirEntry proto.InternalMessageInfo

func (m *DirEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirEntry) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type VolumeSpec struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CellSpec             *CellSpec `protobuf:"bytes,2,opt,name=cell_spec,json=cellSpec,proto3" json:"cell_spec,omitempty"`
	AuxState             []byte    `protobuf:"bytes,3,opt,name=aux_state,json=auxState,proto3" json:"aux_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VolumeSpec) Reset()         { *m = VolumeSpec{} }
func (m *VolumeSpec) String() string { return proto.CompactTextString(m) }
func (*VolumeSpec) ProtoMessage()    {}
func (*VolumeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{4}
}

func (m *VolumeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSpec.Unmarshal(m, b)
}
func (m *VolumeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSpec.Marshal(b, m, deterministic)
}
func (m *VolumeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSpec.Merge(m, src)
}
func (m *VolumeSpec) XXX_Size() int {
	return xxx_messageInfo_VolumeSpec.Size(m)
}
func (m *VolumeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSpec proto.InternalMessageInfo

func (m *VolumeSpec) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VolumeSpec) GetCellSpec() *CellSpec {
	if m != nil {
		return m.CellSpec
	}
	return nil
}

func (m *VolumeSpec) GetAuxState() []byte {
	if m != nil {
		return m.AuxState
	}
	return nil
}

type Commit struct {
	ObjectRef            *webref.Ref `protobuf:"bytes,1,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	Options              *Options    `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{5}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetObjectRef() *webref.Ref {
	if m != nil {
		return m.ObjectRef
	}
	return nil
}

func (m *Commit) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Volume Options
type Options struct {
	DataOpts             *WriteOptions `protobuf:"bytes,1,opt,name=data_opts,json=dataOpts,proto3" json:"data_opts,omitempty"`
	MetadataOpts         *WriteOptions `protobuf:"bytes,2,opt,name=metadata_opts,json=metadataOpts,proto3" json:"metadata_opts,omitempty"`
	StoreSpecs           []*StoreSpec  `protobuf:"bytes,3,rep,name=store_specs,json=storeSpecs,proto3" json:"store_specs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{6}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetDataOpts() *WriteOptions {
	if m != nil {
		return m.DataOpts
	}
	return nil
}

func (m *Options) GetMetadataOpts() *WriteOptions {
	if m != nil {
		return m.MetadataOpts
	}
	return nil
}

func (m *Options) GetStoreSpecs() []*StoreSpec {
	if m != nil {
		return m.StoreSpecs
	}
	return nil
}

type WriteOptions struct {
	EncAlgo              webref.EncAlgo   `protobuf:"varint,1,opt,name=enc_algo,json=encAlgo,proto3,enum=webref.EncAlgo" json:"enc_algo,omitempty"`
	SecretSeed           []byte           `protobuf:"bytes,2,opt,name=secret_seed,json=secretSeed,proto3" json:"secret_seed,omitempty"`
	ObfuscateLength      bool             `protobuf:"varint,3,opt,name=obfuscate_length,json=obfuscateLength,proto3" json:"obfuscate_length,omitempty"`
	Replicas             map[string]int32 `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Codec                string           `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WriteOptions) Reset()         { *m = WriteOptions{} }
func (m *WriteOptions) String() string { return proto.CompactTextString(m) }
func (*WriteOptions) ProtoMessage()    {}
func (*WriteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{7}
}

func (m *WriteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteOptions.Unmarshal(m, b)
}
func (m *WriteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteOptions.Marshal(b, m, deterministic)
}
func (m *WriteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteOptions.Merge(m, src)
}
func (m *WriteOptions) XXX_Size() int {
	return xxx_messageInfo_WriteOptions.Size(m)
}
func (m *WriteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WriteOptions proto.InternalMessageInfo

func (m *WriteOptions) GetEncAlgo() webref.EncAlgo {
	if m != nil {
		return m.EncAlgo
	}
	return webref.EncAlgo_UNKNOWN_EA
}

func (m *WriteOptions) GetSecretSeed() []byte {
	if m != nil {
		return m.SecretSeed
	}
	return nil
}

func (m *WriteOptions) GetObfuscateLength() bool {
	if m != nil {
		return m.ObfuscateLength
	}
	return false
}

func (m *WriteOptions) GetReplicas() map[string]int32 {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *WriteOptions) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

type StoreSpec struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Types that are valid to be assigned to Spec:
	//	*StoreSpec_Http
	//	*StoreSpec_Ipfs
	Spec                 isStoreSpec_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StoreSpec) Reset()         { *m = StoreSpec{} }
func (m *StoreSpec) String() string { return proto.CompactTextString(m) }
func (*StoreSpec) ProtoMessage()    {}
func (*StoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{8}
}

func (m *StoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreSpec.Unmarshal(m, b)
}
func (m *StoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreSpec.Marshal(b, m, deterministic)
}
func (m *StoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreSpec.Merge(m, src)
}
func (m *StoreSpec) XXX_Size() int {
	return xxx_messageInfo_StoreSpec.Size(m)
}
func (m *StoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_StoreSpec proto.InternalMessageInfo

func (m *StoreSpec) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type isStoreSpec_Spec interface {
	isStoreSpec_Spec()
}

type StoreSpec_Http struct {
	Http *HTTPStoreSpec `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type StoreSpec_Ipfs struct {
	Ipfs *IPFSStoreSpec `protobuf:"bytes,3,opt,name=ipfs,proto3,oneof"`
}

func (*StoreSpec_Http) isStoreSpec_Spec() {}

func (*StoreSpec_Ipfs) isStoreSpec_Spec() {}

func (m *StoreSpec) GetSpec() isStoreSpec_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *StoreSpec) GetHttp() *HTTPStoreSpec {
	if x, ok := m.GetSpec().(*StoreSpec_Http); ok {
		return x.Http
	}
	return nil
}

func (m *StoreSpec) GetIpfs() *IPFSStoreSpec {
	if x, ok := m.GetSpec().(*StoreSpec_Ipfs); ok {
		return x.Ipfs
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StoreSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StoreSpec_Http)(nil),
		(*StoreSpec_Ipfs)(nil),
	}
}

func init() {
	proto.RegisterType((*Object)(nil), "webfs.Object")
	proto.RegisterType((*File)(nil), "webfs.File")
	proto.RegisterType((*Dir)(nil), "webfs.Dir")
	proto.RegisterType((*DirEntry)(nil), "webfs.DirEntry")
	proto.RegisterType((*VolumeSpec)(nil), "webfs.VolumeSpec")
	proto.RegisterType((*Commit)(nil), "webfs.Commit")
	proto.RegisterType((*Options)(nil), "webfs.Options")
	proto.RegisterType((*WriteOptions)(nil), "webfs.WriteOptions")
	proto.RegisterMapType((map[string]int32)(nil), "webfs.WriteOptions.ReplicasEntry")
	proto.RegisterType((*StoreSpec)(nil), "webfs.StoreSpec")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_7da965bc36916fc1) }

var fileDescriptor_7da965bc36916fc1 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x6d, 0x12, 0xc7, 0xb1, 0x27, 0x49, 0x9b, 0x6f, 0xbf, 0x0a, 0x45, 0x41, 0x82, 0xd6, 0x52,
	0xa5, 0x52, 0x50, 0x04, 0xe5, 0xa6, 0x2a, 0xe2, 0x82, 0xfe, 0x29, 0x48, 0x48, 0xad, 0x36, 0x55,
	0x91, 0xb8, 0xc0, 0x72, 0xec, 0x71, 0xba, 0xe0, 0x64, 0xad, 0xdd, 0x4d, 0x7f, 0xb8, 0x43, 0xbc,
	0x04, 0x8f, 0xc0, 0x63, 0xa2, 0xfd, 0x71, 0xda, 0x4a, 0x20, 0xee, 0x66, 0xcf, 0x9c, 0x33, 0x3b,
	0x73, 0x66, 0x6d, 0xe8, 0xf2, 0xc9, 0x17, 0x4c, 0x95, 0x1c, 0x96, 0x82, 0x2b, 0x4e, 0x9a, 0xd7,
	0x38, 0xc9, 0xe5, 0x00, 0x94, 0x40, 0xb4, 0xd0, 0x20, 0x14, 0x98, 0xbb, 0xb0, 0x27, 0x15, 0x17,
	0x28, 0x4b, 0x4c, 0x1d, 0x7f, 0xb0, 0x96, 0x62, 0x51, 0xdc, 0x03, 0xa2, 0xef, 0x35, 0xf0, 0x4f,
	0x4d, 0x49, 0xb2, 0x09, 0x5e, 0xce, 0x0a, 0xec, 0xd7, 0x36, 0x6a, 0xdb, 0xed, 0xdd, 0xf6, 0xd0,
	0x94, 0x1e, 0x9e, 0xb0, 0x02, 0x47, 0x2b, 0xd4, 0xa4, 0xc8, 0x13, 0x68, 0x64, 0x4c, 0xf4, 0xeb,
	0x86, 0x01, 0x8e, 0x71, 0xc4, 0xc4, 0x68, 0x85, 0xea, 0x04, 0x79, 0x0e, 0xfe, 0x15, 0x2f, 0x16,
	0x33, 0xec, 0x37, 0x0c, 0xe5, 0x3f, 0x47, 0xb9, 0x30, 0xe0, 0xb8, 0xc4, 0x74, 0xb4, 0x42, 0x1d,
	0xe5, 0xa0, 0x05, 0xcd, 0x8b, 0xa4, 0x58, 0x60, 0xb4, 0x0f, 0xde, 0x89, 0xad, 0xee, 0xe9, 0x39,
	0x5c, 0x03, 0x30, 0xbc, 0x16, 0x99, 0x1c, 0x9e, 0x0b, 0x44, 0x6a, 0x70, 0x42, 0xc0, 0x93, 0xec,
	0x1b, 0x9a, 0xeb, 0x3d, 0x6a, 0xe2, 0x68, 0x0b, 0x1a, 0x47, 0x4c, 0xfc, 0x4b, 0x1a, 0x1d, 0x43,
	0x70, 0xc4, 0xc4, 0xf1, 0x5c, 0x89, 0x5b, 0x5d, 0x66, 0x9e, 0xcc, 0x2c, 0x37, 0xa4, 0x26, 0x26,
	0x5b, 0xe0, 0x5b, 0x63, 0xdd, 0x6c, 0x5d, 0xd7, 0xb8, 0xb5, 0x86, 0xba, 0x64, 0x34, 0x05, 0xb8,
	0x1b, 0x85, 0xac, 0x42, 0x9d, 0x65, 0xae, 0x4c, 0x9d, 0x65, 0xe4, 0x05, 0x84, 0xda, 0xde, 0x58,
	0xfb, 0xeb, 0xea, 0xac, 0xb9, 0x3a, 0x87, 0x58, 0x14, 0x5a, 0x43, 0x83, 0xd4, 0x45, 0xe4, 0x31,
	0x84, 0xc9, 0xe2, 0x26, 0x96, 0x2a, 0x51, 0xd6, 0xae, 0x0e, 0x0d, 0x92, 0xc5, 0xcd, 0x58, 0x9f,
	0xa3, 0xcf, 0xe0, 0x1f, 0xf2, 0xd9, 0x8c, 0x29, 0xb2, 0x03, 0x60, 0x2f, 0x8f, 0x05, 0xe6, 0xf7,
	0x77, 0xa3, 0xd7, 0x4c, 0x31, 0xa7, 0xa1, 0x4d, 0x53, 0xcc, 0xc9, 0x36, 0xb4, 0x78, 0xa9, 0x18,
	0x9f, 0x4b, 0x77, 0xfd, 0x6a, 0x35, 0x86, 0x45, 0x69, 0x95, 0x8e, 0x7e, 0xd5, 0xa0, 0xe5, 0x40,
	0xf2, 0x12, 0xc2, 0x2c, 0x51, 0x49, 0xcc, 0x4b, 0x25, 0xdd, 0x05, 0xff, 0x3b, 0xdd, 0x47, 0xc1,
	0x14, 0x56, 0xe2, 0x40, 0xb3, 0x4e, 0x4b, 0x25, 0xc9, 0x1e, 0x74, 0x67, 0xa8, 0x92, 0x3b, 0x55,
	0xfd, 0xef, 0xaa, 0x4e, 0xc5, 0x34, 0xca, 0x57, 0xd0, 0x36, 0x6f, 0xd2, 0x78, 0x24, 0xfb, 0x8d,
	0x8d, 0xc6, 0x76, 0x7b, 0xb7, 0xe7, 0x74, 0x63, 0x9d, 0x31, 0x2e, 0x81, 0xac, 0x42, 0x19, 0xfd,
	0xac, 0x43, 0xe7, 0x7e, 0x45, 0xb2, 0x03, 0x01, 0xce, 0xd3, 0x38, 0x29, 0xa6, 0xdc, 0xb4, 0xbb,
	0x6a, 0x5d, 0xd6, 0x7e, 0x1c, 0xcf, 0xd3, 0x77, 0xc5, 0x94, 0xd3, 0x16, 0xda, 0x80, 0x3c, 0x85,
	0xb6, 0xc4, 0x54, 0xa0, 0x8a, 0x25, 0x62, 0x66, 0xfa, 0xec, 0x50, 0xb0, 0xd0, 0x18, 0x31, 0x23,
	0xcf, 0xa0, 0xc7, 0x27, 0xf9, 0x42, 0xa6, 0x89, 0xc2, 0xb8, 0xc0, 0xf9, 0x54, 0x5d, 0x9a, 0x65,
	0x04, 0x74, 0x6d, 0x89, 0x7f, 0x30, 0x30, 0x79, 0x0b, 0x81, 0xc0, 0xb2, 0x60, 0x69, 0x22, 0xfb,
	0x9e, 0x69, 0x7c, 0xf3, 0x0f, 0x03, 0x0f, 0xa9, 0xe3, 0x98, 0xc7, 0x46, 0x97, 0x12, 0xb2, 0x0e,
	0xcd, 0x94, 0x67, 0x98, 0xf6, 0x9b, 0xe6, 0xc1, 0xd8, 0xc3, 0xe0, 0x0d, 0x74, 0x1f, 0x08, 0x48,
	0x0f, 0x1a, 0x5f, 0xf1, 0xd6, 0xbd, 0x2a, 0x1d, 0x6a, 0xe1, 0x95, 0xfe, 0x4e, 0x4c, 0xf7, 0x4d,
	0x6a, 0x0f, 0xfb, 0xf5, 0xbd, 0x5a, 0xf4, 0xa3, 0x06, 0xe1, 0xd2, 0x34, 0xf2, 0x08, 0xfc, 0x52,
	0x60, 0xce, 0x6e, 0x9c, 0xd8, 0x9d, 0xc8, 0x0e, 0x78, 0x97, 0x4a, 0x95, 0x6e, 0x49, 0xeb, 0xae,
	0xe7, 0xd1, 0xf9, 0xf9, 0xd9, 0x52, 0xab, 0x3f, 0x70, 0xcd, 0xd1, 0x5c, 0x56, 0xe6, 0xd2, 0x7d,
	0xbe, 0x15, 0xf7, 0xfd, 0xd9, 0xc9, 0xf8, 0x01, 0x57, 0x73, 0x0e, 0x7c, 0xf0, 0xf4, 0x16, 0x0f,
	0xc2, 0x4f, 0x2d, 0x43, 0x63, 0xb3, 0x89, 0x6f, 0x7e, 0x2a, 0xaf, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x1a, 0x91, 0x98, 0xc3, 0xa6, 0x04, 0x00, 0x00,
}
