// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storespecs.proto

package webfsim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HTTPStoreSpec struct {
	Prefix               string            `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Endpoint             string            `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HTTPStoreSpec) Reset()         { *m = HTTPStoreSpec{} }
func (m *HTTPStoreSpec) String() string { return proto.CompactTextString(m) }
func (*HTTPStoreSpec) ProtoMessage()    {}
func (*HTTPStoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa63631e8ee8544c, []int{0}
}

func (m *HTTPStoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPStoreSpec.Unmarshal(m, b)
}
func (m *HTTPStoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPStoreSpec.Marshal(b, m, deterministic)
}
func (m *HTTPStoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPStoreSpec.Merge(m, src)
}
func (m *HTTPStoreSpec) XXX_Size() int {
	return xxx_messageInfo_HTTPStoreSpec.Size(m)
}
func (m *HTTPStoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPStoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPStoreSpec proto.InternalMessageInfo

func (m *HTTPStoreSpec) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *HTTPStoreSpec) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *HTTPStoreSpec) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type IPFSStoreSpec struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPFSStoreSpec) Reset()         { *m = IPFSStoreSpec{} }
func (m *IPFSStoreSpec) String() string { return proto.CompactTextString(m) }
func (*IPFSStoreSpec) ProtoMessage()    {}
func (*IPFSStoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa63631e8ee8544c, []int{1}
}

func (m *IPFSStoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPFSStoreSpec.Unmarshal(m, b)
}
func (m *IPFSStoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPFSStoreSpec.Marshal(b, m, deterministic)
}
func (m *IPFSStoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPFSStoreSpec.Merge(m, src)
}
func (m *IPFSStoreSpec) XXX_Size() int {
	return xxx_messageInfo_IPFSStoreSpec.Size(m)
}
func (m *IPFSStoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_IPFSStoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_IPFSStoreSpec proto.InternalMessageInfo

func (m *IPFSStoreSpec) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*HTTPStoreSpec)(nil), "webfs.HTTPStoreSpec")
	proto.RegisterMapType((map[string]string)(nil), "webfs.HTTPStoreSpec.HeadersEntry")
	proto.RegisterType((*IPFSStoreSpec)(nil), "webfs.IPFSStoreSpec")
}

func init() { proto.RegisterFile("storespecs.proto", fileDescriptor_fa63631e8ee8544c) }

var fileDescriptor_fa63631e8ee8544c = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2e, 0xc9, 0x2f,
	0x4a, 0x2d, 0x2e, 0x48, 0x4d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4f,
	0x4d, 0x4a, 0x2b, 0x56, 0xda, 0xc3, 0xc8, 0xc5, 0xeb, 0x11, 0x12, 0x12, 0x10, 0x0c, 0x92, 0x0f,
	0x2e, 0x48, 0x4d, 0x16, 0x12, 0xe3, 0x62, 0x2b, 0x28, 0x4a, 0x4d, 0xcb, 0xac, 0x90, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x52, 0xf3, 0x52, 0x0a, 0xf2, 0x33,
	0xf3, 0x4a, 0x24, 0x98, 0xc0, 0x32, 0x70, 0xbe, 0x90, 0x35, 0x17, 0x7b, 0x46, 0x6a, 0x62, 0x4a,
	0x6a, 0x51, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa2, 0x1e, 0xd8, 0x78, 0x3d, 0x14,
	0xa3, 0xf5, 0x3c, 0x20, 0x6a, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0x83, 0x60, 0x3a, 0xa4, 0xac, 0xb8,
	0x78, 0x90, 0x25, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xa1, 0xb6, 0x83, 0x98, 0x42, 0x22,
	0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x50, 0x7b, 0x21, 0x1c, 0x2b, 0x26, 0x0b, 0x46, 0x25,
	0x6d, 0x2e, 0x5e, 0xcf, 0x00, 0xb7, 0x60, 0x84, 0xeb, 0x91, 0x5d, 0xc9, 0x88, 0xea, 0x4a, 0x27,
	0xce, 0x28, 0x76, 0xb0, 0xab, 0x32, 0x73, 0x93, 0xd8, 0xc0, 0x81, 0x60, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xfe, 0x4c, 0x97, 0x11, 0x18, 0x01, 0x00, 0x00,
}
