// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storespecs.proto

package webfsim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreSpec struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Types that are valid to be assigned to Spec:
	//	*StoreSpec_Http
	//	*StoreSpec_Ipfs
	Spec                 isStoreSpec_Spec `protobuf_oneof:"spec"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StoreSpec) Reset()         { *m = StoreSpec{} }
func (m *StoreSpec) String() string { return proto.CompactTextString(m) }
func (*StoreSpec) ProtoMessage()    {}
func (*StoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa63631e8ee8544c, []int{0}
}

func (m *StoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreSpec.Unmarshal(m, b)
}
func (m *StoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreSpec.Marshal(b, m, deterministic)
}
func (m *StoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreSpec.Merge(m, src)
}
func (m *StoreSpec) XXX_Size() int {
	return xxx_messageInfo_StoreSpec.Size(m)
}
func (m *StoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_StoreSpec proto.InternalMessageInfo

func (m *StoreSpec) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type isStoreSpec_Spec interface {
	isStoreSpec_Spec()
}

type StoreSpec_Http struct {
	Http *HTTPStoreSpec `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type StoreSpec_Ipfs struct {
	Ipfs *IPFSStoreSpec `protobuf:"bytes,3,opt,name=ipfs,proto3,oneof"`
}

func (*StoreSpec_Http) isStoreSpec_Spec() {}

func (*StoreSpec_Ipfs) isStoreSpec_Spec() {}

func (m *StoreSpec) GetSpec() isStoreSpec_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *StoreSpec) GetHttp() *HTTPStoreSpec {
	if x, ok := m.GetSpec().(*StoreSpec_Http); ok {
		return x.Http
	}
	return nil
}

func (m *StoreSpec) GetIpfs() *IPFSStoreSpec {
	if x, ok := m.GetSpec().(*StoreSpec_Ipfs); ok {
		return x.Ipfs
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StoreSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StoreSpec_Http)(nil),
		(*StoreSpec_Ipfs)(nil),
	}
}

type HTTPStoreSpec struct {
	Endpoint             string            `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HTTPStoreSpec) Reset()         { *m = HTTPStoreSpec{} }
func (m *HTTPStoreSpec) String() string { return proto.CompactTextString(m) }
func (*HTTPStoreSpec) ProtoMessage()    {}
func (*HTTPStoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa63631e8ee8544c, []int{1}
}

func (m *HTTPStoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPStoreSpec.Unmarshal(m, b)
}
func (m *HTTPStoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPStoreSpec.Marshal(b, m, deterministic)
}
func (m *HTTPStoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPStoreSpec.Merge(m, src)
}
func (m *HTTPStoreSpec) XXX_Size() int {
	return xxx_messageInfo_HTTPStoreSpec.Size(m)
}
func (m *HTTPStoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPStoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPStoreSpec proto.InternalMessageInfo

func (m *HTTPStoreSpec) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *HTTPStoreSpec) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type IPFSStoreSpec struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPFSStoreSpec) Reset()         { *m = IPFSStoreSpec{} }
func (m *IPFSStoreSpec) String() string { return proto.CompactTextString(m) }
func (*IPFSStoreSpec) ProtoMessage()    {}
func (*IPFSStoreSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa63631e8ee8544c, []int{2}
}

func (m *IPFSStoreSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPFSStoreSpec.Unmarshal(m, b)
}
func (m *IPFSStoreSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPFSStoreSpec.Marshal(b, m, deterministic)
}
func (m *IPFSStoreSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPFSStoreSpec.Merge(m, src)
}
func (m *IPFSStoreSpec) XXX_Size() int {
	return xxx_messageInfo_IPFSStoreSpec.Size(m)
}
func (m *IPFSStoreSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_IPFSStoreSpec.DiscardUnknown(m)
}

var xxx_messageInfo_IPFSStoreSpec proto.InternalMessageInfo

func (m *IPFSStoreSpec) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*StoreSpec)(nil), "webfs.StoreSpec")
	proto.RegisterType((*HTTPStoreSpec)(nil), "webfs.HTTPStoreSpec")
	proto.RegisterMapType((map[string]string)(nil), "webfs.HTTPStoreSpec.HeadersEntry")
	proto.RegisterType((*IPFSStoreSpec)(nil), "webfs.IPFSStoreSpec")
}

func init() { proto.RegisterFile("storespecs.proto", fileDescriptor_fa63631e8ee8544c) }

var fileDescriptor_fa63631e8ee8544c = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2e, 0xc9, 0x2f,
	0x4a, 0x2d, 0x2e, 0x48, 0x4d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4f,
	0x4d, 0x4a, 0x2b, 0x56, 0x6a, 0x66, 0xe4, 0xe2, 0x0c, 0x06, 0xc9, 0x05, 0x17, 0xa4, 0x26, 0x0b,
	0x89, 0x71, 0xb1, 0x15, 0x14, 0xa5, 0xa6, 0x65, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x41, 0x79, 0x42, 0x5a, 0x5c, 0x2c, 0x19, 0x25, 0x25, 0x05, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0x22, 0x7a, 0x60, 0xbd, 0x7a, 0x1e, 0x21, 0x21, 0x01, 0x70, 0xbd, 0x1e, 0x0c, 0x41, 0x60,
	0x35, 0x20, 0xb5, 0x99, 0x05, 0x69, 0xc5, 0x12, 0xcc, 0x28, 0x6a, 0x3d, 0x03, 0xdc, 0x82, 0x51,
	0xd4, 0x82, 0xd4, 0x38, 0xb1, 0x71, 0xb1, 0x80, 0xdc, 0xa4, 0xb4, 0x84, 0x91, 0x8b, 0x17, 0xc5,
	0x34, 0x21, 0x29, 0x2e, 0x8e, 0xd4, 0xbc, 0x94, 0x82, 0xfc, 0xcc, 0xbc, 0x12, 0xa8, 0x5b, 0xe0,
	0x7c, 0x21, 0x6b, 0x2e, 0xf6, 0x8c, 0xd4, 0xc4, 0x94, 0xd4, 0xa2, 0x62, 0x09, 0x26, 0x05, 0x66,
	0x0d, 0x6e, 0x23, 0x45, 0x6c, 0x0e, 0xd2, 0xf3, 0x80, 0xa8, 0x71, 0xcd, 0x2b, 0x29, 0xaa, 0x0c,
	0x82, 0xe9, 0x90, 0xb2, 0xe2, 0xe2, 0x41, 0x96, 0x10, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x84,
	0xda, 0x01, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x82, 0x7d, 0xcb, 0x19,
	0x04, 0xe1, 0x58, 0x31, 0x59, 0x30, 0x2a, 0x69, 0x73, 0xf1, 0xa2, 0xf8, 0x03, 0x9f, 0x2b, 0x9d,
	0x38, 0xa3, 0xd8, 0xc1, 0xae, 0xca, 0xcc, 0x4d, 0x62, 0x03, 0x07, 0xb9, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xc4, 0xb8, 0x6e, 0x0f, 0x86, 0x01, 0x00, 0x00,
}
