// Code generated by capnpc-go. DO NOT EDIT.

package wfscnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type TypeCode uint16

// TypeCode_TypeID is the unique identifier for the type TypeCode.
const TypeCode_TypeID = 0x9d76b4edf5de8a4f

// Values of TypeCode.
const (
	TypeCode_unknown     TypeCode = 0
	TypeCode_regularFile TypeCode = 1
	TypeCode_dir         TypeCode = 2
	TypeCode_volumeLink  TypeCode = 3
)

// String returns the enum's constant name.
func (c TypeCode) String() string {
	switch c {
	case TypeCode_unknown:
		return "unknown"
	case TypeCode_regularFile:
		return "regularFile"
	case TypeCode_dir:
		return "dir"
	case TypeCode_volumeLink:
		return "volumeLink"

	default:
		return ""
	}
}

// TypeCodeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TypeCodeFromString(c string) TypeCode {
	switch c {
	case "unknown":
		return TypeCode_unknown
	case "regularFile":
		return TypeCode_regularFile
	case "dir":
		return TypeCode_dir
	case "volumeLink":
		return TypeCode_volumeLink

	default:
		return 0
	}
}

type TypeCode_List = capnp.EnumList[TypeCode]

func NewTypeCode_List(s *capnp.Segment, sz int32) (TypeCode_List, error) {
	return capnp.NewEnumList[TypeCode](s, sz)
}

type TAI64N capnp.Struct

// TAI64N_TypeID is the unique identifier for the type TAI64N.
const TAI64N_TypeID = 0xcb1372662c30a824

func NewTAI64N(s *capnp.Segment) (TAI64N, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return TAI64N(st), err
}

func NewRootTAI64N(s *capnp.Segment) (TAI64N, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return TAI64N(st), err
}

func ReadRootTAI64N(msg *capnp.Message) (TAI64N, error) {
	root, err := msg.Root()
	return TAI64N(root.Struct()), err
}

func (s TAI64N) String() string {
	str, _ := text.Marshal(0xcb1372662c30a824, capnp.Struct(s))
	return str
}

func (s TAI64N) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TAI64N) DecodeFromPtr(p capnp.Ptr) TAI64N {
	return TAI64N(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TAI64N) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TAI64N) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TAI64N) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TAI64N) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TAI64N) Seconds() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s TAI64N) SetSeconds(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s TAI64N) Nanoseconds() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s TAI64N) SetNanoseconds(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// TAI64N_List is a list of TAI64N.
type TAI64N_List = capnp.StructList[TAI64N]

// NewTAI64N creates a new list of TAI64N.
func NewTAI64N_List(s *capnp.Segment, sz int32) (TAI64N_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[TAI64N](l), err
}

// TAI64N_Future is a wrapper for a TAI64N promised by a client call.
type TAI64N_Future struct{ *capnp.Future }

func (f TAI64N_Future) Struct() (TAI64N, error) {
	p, err := f.Future.Ptr()
	return TAI64N(p.Struct()), err
}

type Node capnp.Struct
type Node_payload Node
type Node_payload_Which uint16

const (
	Node_payload_Which_file       Node_payload_Which = 0
	Node_payload_Which_dir        Node_payload_Which = 1
	Node_payload_Which_volumeLink Node_payload_Which = 2
)

func (w Node_payload_Which) String() string {
	const s = "filedirvolumeLink"
	switch w {
	case Node_payload_Which_file:
		return s[0:4]
	case Node_payload_Which_dir:
		return s[4:7]
	case Node_payload_Which_volumeLink:
		return s[7:17]

	}
	return "Node_payload_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Node_TypeID is the unique identifier for the type Node.
const Node_TypeID = 0xce73733f540a13ee

func NewNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return Node(st), err
}

func NewRootNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return Node(st), err
}

func ReadRootNode(msg *capnp.Message) (Node, error) {
	root, err := msg.Root()
	return Node(root.Struct()), err
}

func (s Node) String() string {
	str, _ := text.Marshal(0xce73733f540a13ee, capnp.Struct(s))
	return str
}

func (s Node) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Node) DecodeFromPtr(p capnp.Ptr) Node {
	return Node(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Node) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Node) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node) CreatedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return TAI64N(p.Struct()), err
}

func (s Node) HasCreatedAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Node) SetCreatedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCreatedAt sets the createdAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Node) NewCreatedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node) ModifiedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TAI64N(p.Struct()), err
}

func (s Node) HasModifiedAt() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Node) SetModifiedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewModifiedAt sets the modifiedAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Node) NewModifiedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node) RefCount() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Node) SetRefCount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Node) Rev() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Node) SetRev(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Node) Mode() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s Node) SetMode(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

func (s Node) Payload() Node_payload { return Node_payload(s) }

func (s Node_payload) Which() Node_payload_Which {
	return Node_payload_Which(capnp.Struct(s).Uint16(4))
}
func (s Node_payload) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node_payload) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node_payload) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node_payload) File() (File, error) {
	if capnp.Struct(s).Uint16(4) != 0 {
		panic("Which() != file")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return File(p.Struct()), err
}

func (s Node_payload) HasFile() bool {
	if capnp.Struct(s).Uint16(4) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetFile(v File) error {
	capnp.Struct(s).SetUint16(4, 0)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewFile sets the file field to a newly
// allocated File struct, preferring placement in s's segment.
func (s Node_payload) NewFile() (File, error) {
	capnp.Struct(s).SetUint16(4, 0)
	ss, err := NewFile(capnp.Struct(s).Segment())
	if err != nil {
		return File{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node_payload) Dir() (Dir, error) {
	if capnp.Struct(s).Uint16(4) != 1 {
		panic("Which() != dir")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return Dir(p.Struct()), err
}

func (s Node_payload) HasDir() bool {
	if capnp.Struct(s).Uint16(4) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetDir(v Dir) error {
	capnp.Struct(s).SetUint16(4, 1)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewDir sets the dir field to a newly
// allocated Dir struct, preferring placement in s's segment.
func (s Node_payload) NewDir() (Dir, error) {
	capnp.Struct(s).SetUint16(4, 1)
	ss, err := NewDir(capnp.Struct(s).Segment())
	if err != nil {
		return Dir{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node_payload) VolumeLink() (VolumeLink, error) {
	if capnp.Struct(s).Uint16(4) != 2 {
		panic("Which() != volumeLink")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return VolumeLink(p.Struct()), err
}

func (s Node_payload) HasVolumeLink() bool {
	if capnp.Struct(s).Uint16(4) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetVolumeLink(v VolumeLink) error {
	capnp.Struct(s).SetUint16(4, 2)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewVolumeLink sets the volumeLink field to a newly
// allocated VolumeLink struct, preferring placement in s's segment.
func (s Node_payload) NewVolumeLink() (VolumeLink, error) {
	capnp.Struct(s).SetUint16(4, 2)
	ss, err := NewVolumeLink(capnp.Struct(s).Segment())
	if err != nil {
		return VolumeLink{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Node_List is a list of Node.
type Node_List = capnp.StructList[Node]

// NewNode creates a new list of Node.
func NewNode_List(s *capnp.Segment, sz int32) (Node_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3}, sz)
	return capnp.StructList[Node](l), err
}

// Node_Future is a wrapper for a Node promised by a client call.
type Node_Future struct{ *capnp.Future }

func (f Node_Future) Struct() (Node, error) {
	p, err := f.Future.Ptr()
	return Node(p.Struct()), err
}
func (p Node_Future) CreatedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(0, nil)}
}
func (p Node_Future) ModifiedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(1, nil)}
}
func (p Node_Future) Payload() Node_payload_Future { return Node_payload_Future{p.Future} }

// Node_payload_Future is a wrapper for a Node_payload promised by a client call.
type Node_payload_Future struct{ *capnp.Future }

func (f Node_payload_Future) Struct() (Node_payload, error) {
	p, err := f.Future.Ptr()
	return Node_payload(p.Struct()), err
}
func (p Node_payload_Future) File() File_Future {
	return File_Future{Future: p.Future.Field(2, nil)}
}
func (p Node_payload_Future) Dir() Dir_Future {
	return Dir_Future{Future: p.Future.Field(2, nil)}
}
func (p Node_payload_Future) VolumeLink() VolumeLink_Future {
	return VolumeLink_Future{Future: p.Future.Field(2, nil)}
}

type Dir capnp.Struct

// Dir_TypeID is the unique identifier for the type Dir.
const Dir_TypeID = 0xd32874a2d92eaae5

func NewDir(s *capnp.Segment) (Dir, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Dir(st), err
}

func NewRootDir(s *capnp.Segment) (Dir, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Dir(st), err
}

func ReadRootDir(msg *capnp.Message) (Dir, error) {
	root, err := msg.Root()
	return Dir(root.Struct()), err
}

func (s Dir) String() string {
	str, _ := text.Marshal(0xd32874a2d92eaae5, capnp.Struct(s))
	return str
}

func (s Dir) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Dir) DecodeFromPtr(p capnp.Ptr) Dir {
	return Dir(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Dir) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Dir) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Dir) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Dir) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Dir_List is a list of Dir.
type Dir_List = capnp.StructList[Dir]

// NewDir creates a new list of Dir.
func NewDir_List(s *capnp.Segment, sz int32) (Dir_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Dir](l), err
}

// Dir_Future is a wrapper for a Dir promised by a client call.
type Dir_Future struct{ *capnp.Future }

func (f Dir_Future) Struct() (Dir, error) {
	p, err := f.Future.Ptr()
	return Dir(p.Struct()), err
}

type File capnp.Struct

// File_TypeID is the unique identifier for the type File.
const File_TypeID = 0xa54866ce4ae19c91

func NewFile(s *capnp.Segment) (File, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return File(st), err
}

func NewRootFile(s *capnp.Segment) (File, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return File(st), err
}

func ReadRootFile(msg *capnp.Message) (File, error) {
	root, err := msg.Root()
	return File(root.Struct()), err
}

func (s File) String() string {
	str, _ := text.Marshal(0xa54866ce4ae19c91, capnp.Struct(s))
	return str
}

func (s File) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (File) DecodeFromPtr(p capnp.Ptr) File {
	return File(capnp.Struct{}.DecodeFromPtr(p))
}

func (s File) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s File) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s File) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s File) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s File) Size() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s File) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s File) BlockSize() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s File) SetBlockSize(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// File_List is a list of File.
type File_List = capnp.StructList[File]

// NewFile creates a new list of File.
func NewFile_List(s *capnp.Segment, sz int32) (File_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[File](l), err
}

// File_Future is a wrapper for a File promised by a client call.
type File_Future struct{ *capnp.Future }

func (f File_Future) Struct() (File, error) {
	p, err := f.Future.Ptr()
	return File(p.Struct()), err
}

type VolumeLink capnp.Struct

// VolumeLink_TypeID is the unique identifier for the type VolumeLink.
const VolumeLink_TypeID = 0xaaf625b443435e37

func NewVolumeLink(s *capnp.Segment) (VolumeLink, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VolumeLink(st), err
}

func NewRootVolumeLink(s *capnp.Segment) (VolumeLink, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VolumeLink(st), err
}

func ReadRootVolumeLink(msg *capnp.Message) (VolumeLink, error) {
	root, err := msg.Root()
	return VolumeLink(root.Struct()), err
}

func (s VolumeLink) String() string {
	str, _ := text.Marshal(0xaaf625b443435e37, capnp.Struct(s))
	return str
}

func (s VolumeLink) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VolumeLink) DecodeFromPtr(p capnp.Ptr) VolumeLink {
	return VolumeLink(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VolumeLink) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VolumeLink) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VolumeLink) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VolumeLink) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VolumeLink) NodeID() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s VolumeLink) HasNodeID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VolumeLink) SetNodeID(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s VolumeLink) Oid() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s VolumeLink) HasOid() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s VolumeLink) SetOid(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// VolumeLink_List is a list of VolumeLink.
type VolumeLink_List = capnp.StructList[VolumeLink]

// NewVolumeLink creates a new list of VolumeLink.
func NewVolumeLink_List(s *capnp.Segment, sz int32) (VolumeLink_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[VolumeLink](l), err
}

// VolumeLink_Future is a wrapper for a VolumeLink promised by a client call.
type VolumeLink_Future struct{ *capnp.Future }

func (f VolumeLink_Future) Struct() (VolumeLink, error) {
	p, err := f.Future.Ptr()
	return VolumeLink(p.Struct()), err
}

type Session capnp.Struct

// Session_TypeID is the unique identifier for the type Session.
const Session_TypeID = 0x8261a2e190180149

func NewSession(s *capnp.Segment) (Session, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Session(st), err
}

func NewRootSession(s *capnp.Segment) (Session, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Session(st), err
}

func ReadRootSession(msg *capnp.Message) (Session, error) {
	root, err := msg.Root()
	return Session(root.Struct()), err
}

func (s Session) String() string {
	str, _ := text.Marshal(0x8261a2e190180149, capnp.Struct(s))
	return str
}

func (s Session) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Session) DecodeFromPtr(p capnp.Ptr) Session {
	return Session(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Session) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Session) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Session) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Session) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Session) CreateAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return TAI64N(p.Struct()), err
}

func (s Session) HasCreateAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Session) SetCreateAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCreateAt sets the createAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Session) NewCreateAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Session) Ttl() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Session) SetTtl(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Session) PublicKeyRef() (Ref, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Ref(p.Struct()), err
}

func (s Session) HasPublicKeyRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Session) SetPublicKeyRef(v Ref) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPublicKeyRef sets the publicKeyRef field to a newly
// allocated Ref struct, preferring placement in s's segment.
func (s Session) NewPublicKeyRef() (Ref, error) {
	ss, err := NewRef(capnp.Struct(s).Segment())
	if err != nil {
		return Ref{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Session) TouchedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return TAI64N(p.Struct()), err
}

func (s Session) HasTouchedAt() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Session) SetTouchedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewTouchedAt sets the touchedAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Session) NewTouchedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Session_List is a list of Session.
type Session_List = capnp.StructList[Session]

// NewSession creates a new list of Session.
func NewSession_List(s *capnp.Segment, sz int32) (Session_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Session](l), err
}

// Session_Future is a wrapper for a Session promised by a client call.
type Session_Future struct{ *capnp.Future }

func (f Session_Future) Struct() (Session, error) {
	p, err := f.Future.Ptr()
	return Session(p.Struct()), err
}
func (p Session_Future) CreateAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(0, nil)}
}
func (p Session_Future) PublicKeyRef() Ref_Future {
	return Ref_Future{Future: p.Future.Field(1, nil)}
}
func (p Session_Future) TouchedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(2, nil)}
}

type Ref capnp.Struct

// Ref_TypeID is the unique identifier for the type Ref.
const Ref_TypeID = 0xf5abf3a701595ebc

func NewRef(s *capnp.Segment) (Ref, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Ref(st), err
}

func NewRootRef(s *capnp.Segment) (Ref, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Ref(st), err
}

func ReadRootRef(msg *capnp.Message) (Ref, error) {
	root, err := msg.Root()
	return Ref(root.Struct()), err
}

func (s Ref) String() string {
	str, _ := text.Marshal(0xf5abf3a701595ebc, capnp.Struct(s))
	return str
}

func (s Ref) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Ref) DecodeFromPtr(p capnp.Ptr) Ref {
	return Ref(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Ref) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Ref) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Ref) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Ref) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Ref) Cid() (UInt256, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return UInt256(p.Struct()), err
}

func (s Ref) HasCid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Ref) SetCid(v UInt256) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCid sets the cid field to a newly
// allocated UInt256 struct, preferring placement in s's segment.
func (s Ref) NewCid() (UInt256, error) {
	ss, err := NewUInt256(capnp.Struct(s).Segment())
	if err != nil {
		return UInt256{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Ref) Dek() (UInt256, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return UInt256(p.Struct()), err
}

func (s Ref) HasDek() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Ref) SetDek(v UInt256) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewDek sets the dek field to a newly
// allocated UInt256 struct, preferring placement in s's segment.
func (s Ref) NewDek() (UInt256, error) {
	ss, err := NewUInt256(capnp.Struct(s).Segment())
	if err != nil {
		return UInt256{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Ref_List is a list of Ref.
type Ref_List = capnp.StructList[Ref]

// NewRef creates a new list of Ref.
func NewRef_List(s *capnp.Segment, sz int32) (Ref_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Ref](l), err
}

// Ref_Future is a wrapper for a Ref promised by a client call.
type Ref_Future struct{ *capnp.Future }

func (f Ref_Future) Struct() (Ref, error) {
	p, err := f.Future.Ptr()
	return Ref(p.Struct()), err
}
func (p Ref_Future) Cid() UInt256_Future {
	return UInt256_Future{Future: p.Future.Field(0, nil)}
}
func (p Ref_Future) Dek() UInt256_Future {
	return UInt256_Future{Future: p.Future.Field(1, nil)}
}

type UInt256 capnp.Struct

// UInt256_TypeID is the unique identifier for the type UInt256.
const UInt256_TypeID = 0xee049aba672f50cf

func NewUInt256(s *capnp.Segment) (UInt256, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return UInt256(st), err
}

func NewRootUInt256(s *capnp.Segment) (UInt256, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return UInt256(st), err
}

func ReadRootUInt256(msg *capnp.Message) (UInt256, error) {
	root, err := msg.Root()
	return UInt256(root.Struct()), err
}

func (s UInt256) String() string {
	str, _ := text.Marshal(0xee049aba672f50cf, capnp.Struct(s))
	return str
}

func (s UInt256) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UInt256) DecodeFromPtr(p capnp.Ptr) UInt256 {
	return UInt256(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UInt256) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UInt256) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UInt256) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UInt256) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UInt256) A() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s UInt256) SetA(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s UInt256) B() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s UInt256) SetB(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s UInt256) C() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s UInt256) SetC(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s UInt256) D() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s UInt256) SetD(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

// UInt256_List is a list of UInt256.
type UInt256_List = capnp.StructList[UInt256]

// NewUInt256 creates a new list of UInt256.
func NewUInt256_List(s *capnp.Segment, sz int32) (UInt256_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[UInt256](l), err
}

// UInt256_Future is a wrapper for a UInt256 promised by a client call.
type UInt256_Future struct{ *capnp.Future }

func (f UInt256_Future) Struct() (UInt256, error) {
	p, err := f.Future.Ptr()
	return UInt256(p.Struct()), err
}

const schema_8bfbc7e27592cd31 = "x\xda\x84\x94_h\x1cU\x14\xc6\xcfw\xef\xecN*" +
	"\x09\xbb\x93Y\xa1\x0f\xe6\xc1\xd0BS\xba1\xd1\xa6\xd6" +
	"\x82\xa6\xf9\xd3\xea\xd6\xb4\xe6\xa6\x8d\xda \xc5\xdd\x9d\xbb" +
	"\xc9\xb8\xb33\xeb\xeelb\xfa\x12\xc9c|Q\x9f\xb4" +
	"X\xd0\xa0\xb4\xc6\x82\x08\x11\xa4\xf8(H\x95T\x8a\x0f" +
	"\xd2\x17\xa1\x82\xf8d_\xa4\x82\x88\x8e\xdc\xd9\xcd\xce\xee" +
	"v\x8bo\x873g\xcew\xce\xef\xdcsF\x16\xd8q" +
	"m\xb4\xef'\x8d\x988\x1a\x8b\x07\x19\xec}\xfb\xcef" +
	"v\x9dD/\x10\x8c\xee\xbc[\xfb\xe5\xdb\xbf\xdf\xa2\x18" +
	"\xd7\x89L\xc16\xcd\xf3LY\xf3\xec7B\xf0\xc2\xc6" +
	"\xcf\xf7~\xdf^\xbeLF/\x8bb\x09\xe6\x18\xdf2" +
	"\x9f\x0e\x7fy\x8a/\x12\x82w>\xb8s\xeaf\xe1\xb9" +
	"OT\xd6\x96HMEH\xbea\x96\xc2X\x9b\xaf\x10" +
	"\x82'/LMm\xef\xffs\x8b\x8c\xde\xd6\x02B\xd9" +
	"\x1b\xfc\xbay+\x8c\xdd\x09c\xaf<\xfbL\xe9\xaf\x13" +
	"\xb7\xbf!a\x80\x07w\xcd\x87\xce\x8dW\xab7i\x9e" +
	"\xeb\xe0`\xe6\x90\xf6\x1d\xc1Lk\x9f\x13\x82}WG" +
	"\x0e\x15*\xe6\xf7\xddJ\xb8\xa1]2o\x85\xd6\x8e\xa6" +
	"\xd26\x13\x89^\xf0N\x08\xe9\xd8\x869\x16\xd3\x89\x9e" +
	"\x18\x8d\xbd\x04B\xf0\xeb\xd6\xf0\xedM\xff\xc0\x8f\xed\x05" +
	"\x87\xe9J\xf1u\xf3\xf5\xb8N<\xf8a\xf6\xb1\xc5\xeb" +
	"\x97\xb4\xbb*\xa5\xd6\x11u:\xbei\xce\xc7C\xc0q" +
	"\x85\xf5\xeb\x0b\xe7q\xe5\x8f\xcf\xeeu#\xb0__7" +
	"\x87\xf4\xba\xb5B\xe9`E\xe6\x0a\xd5\xe1|\x16e\xb7" +
	"|\xec\xac\xacVu\xdbsg\x01\x91\xe4\x1a\x91\x06\"" +
	"#{\x8aH\xbc\xca!\x1c\x06 \x05\xe5\xb3\x07\x89\x84" +
	"\xc5!\xca\x0c\x06C\x0a\x8c\xc8(\xbdF$\x1c\x0e\xf1" +
	"\x06\x83\xc1Y\x0a\x9c\xc8\xa8\xcd\x11\x09\x9fC\xbc\xc9\x10" +
	"\xe4+2\xeb\xcb\x09\x9f\x88\x90\x8c\x90\x12\x90$\xe8\xbe" +
	"\xef\xa0\x87\x18z\x08A\xb9\x96s\xec\xfc\xf3\x92\x12\xab" +
	"s\xb2\x80d\xd4T=8\xf0\xbdZ~IZ\x13\x04" +
	"\xff\xfeT\xedm\x9d[-\xcb\xc4\x94g\xc9\xb0\xaf\xb0" +
	"\xd4\xa1I\x15i<\x9a#\x023\x06\x06\x89\xc0\x8d\x87" +
	"\x17\x88\xd6jn\xd1\xf5V\xdc\xa0\"\x17kN\xb6r" +
	"\x92t\xdb\x91\xbaeW\x82e\xcf\xa9\x95\xe4\x8cM\xdc" +
	"-\xb6\x0b\x9c\xb4\x1dI\xa4\xb2\xf74\xa9\x0d\x1d$\x12" +
	"\xfb8\xc4\x08\x83\x01V\xc7\x96V0\x0eq\x88\xa3\x0c" +
	"\x89\xaa}Qb\x0f1\xec!\x049\xc7\xcb\x17\xcf\xda" +
	"\x17\x09\xb2\xc9\xa0M\xe3E\xcf\xa9\x8d+y\xb7\xd8!" +
	"t\xacU\xa81\x9f\xb4\x9a\xcf\x01\x0eq\x98a\xdc\xf5" +
	",\x99\x99F\x1f1\xf4\x11t\xcf\xb6v\xed\xa6\x04S" +
	"\x12g<K\x0e\x97\xb3\xab\x8e\x97\xb5\x88D/\xd7\x1e" +
	"\x09\x02\x96\x82Fd\x9cP\xed\x1c\xe7\x103\x0c\x03\xf8" +
	"W\xb9cDFF\xe9Ls\x88Y\x86\x01\xf6\x8fr" +
	"\xc7\x89\x8c\xd3\x0bDb\x86C\xbc\xcc\x90(\xd8\x8eD" +
	"2\xda\xe1\xc6\xb4-\xbb\x82d\xf4\xf8\x1b\x83k\x85\x8c" +
	"d\xb4\xcc]\xe7:\x919\xc2\x0f\x9f\xe9\xc01\xd9\x8d" +
	"{.\xe2\xbeV\x95y\xcf\xb5\xaaM\xf4n\xd6\xf5\x94" +
	"\x8ft\xe5\xed\x0a_\x91\xa9\x0fxoS\xe8}5\xcb" +
	"\xf78\xc4\xc7-\xdc?R\x8d\x7f\xc8!\xae1(q" +
	"\xf5\xd6>U\xfbs\x95Cl\xab\xb5@}-\xbeP" +
	"\xe0\xaeq\x88\xaf\x18\x10C\xcb)2\xbe\x9c$fh" +
	"Z\x0a:\x91q\xf9`\xa4\xd2X\x9f\x07\xbd\xf9\x92g" +
	"\xd9\x05[Z\xc4'\xba}\xae\xc8\xc2\x94Ws\xc3\xdd" +
	"k4\xa9W\xe4\xf2.\x86\xb5\xc6\xe0\x13%\xcfz\xc0" +
	"\x13\x9c\xb6+\x8aA\xbbs>\xe3\xfa\xfa\xe3cG:" +
	"nF?\x91x\x85C,\xb5\xc0\x91\xfd\xd1!1X" +
	"\x83\x8e\xdd\xdfrI8\xaf\xd3))\xe7\x12\x87\xf0\x19" +
	"\x90\xdd-\x11\xb9\xa6\x95oZVs\x8eme\xcd\xc9" +
	"B\xe7B\x0e\xfe\xcf\x9e\xe8y\xdbB2\xba\xb4\xbb\xef" +
	"T\x16\xef\xf7\xfe\x17\x00\x00\xff\xff\x18]\xab\x1c"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_8bfbc7e27592cd31,
		Nodes: []uint64{
			0x8261a2e190180149,
			0x9d76b4edf5de8a4f,
			0xa54866ce4ae19c91,
			0xaaf625b443435e37,
			0xc4d945f96d3e47a7,
			0xcb1372662c30a824,
			0xce73733f540a13ee,
			0xd32874a2d92eaae5,
			0xee049aba672f50cf,
			0xf5abf3a701595ebc,
		},
		Compressed: true,
	})
}
