// Code generated by capnpc-go. DO NOT EDIT.

package wfscnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type TypeCode uint16

// TypeCode_TypeID is the unique identifier for the type TypeCode.
const TypeCode_TypeID = 0x9d76b4edf5de8a4f

// Values of TypeCode.
const (
	TypeCode_unknown     TypeCode = 0
	TypeCode_regularFile TypeCode = 1
	TypeCode_dir         TypeCode = 2
	TypeCode_volumeLink  TypeCode = 3
)

// String returns the enum's constant name.
func (c TypeCode) String() string {
	switch c {
	case TypeCode_unknown:
		return "unknown"
	case TypeCode_regularFile:
		return "regularFile"
	case TypeCode_dir:
		return "dir"
	case TypeCode_volumeLink:
		return "volumeLink"

	default:
		return ""
	}
}

// TypeCodeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TypeCodeFromString(c string) TypeCode {
	switch c {
	case "unknown":
		return TypeCode_unknown
	case "regularFile":
		return TypeCode_regularFile
	case "dir":
		return TypeCode_dir
	case "volumeLink":
		return TypeCode_volumeLink

	default:
		return 0
	}
}

type TypeCode_List = capnp.EnumList[TypeCode]

func NewTypeCode_List(s *capnp.Segment, sz int32) (TypeCode_List, error) {
	return capnp.NewEnumList[TypeCode](s, sz)
}

type TAI64N capnp.Struct

// TAI64N_TypeID is the unique identifier for the type TAI64N.
const TAI64N_TypeID = 0xcb1372662c30a824

func NewTAI64N(s *capnp.Segment) (TAI64N, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return TAI64N(st), err
}

func NewRootTAI64N(s *capnp.Segment) (TAI64N, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return TAI64N(st), err
}

func ReadRootTAI64N(msg *capnp.Message) (TAI64N, error) {
	root, err := msg.Root()
	return TAI64N(root.Struct()), err
}

func (s TAI64N) String() string {
	str, _ := text.Marshal(0xcb1372662c30a824, capnp.Struct(s))
	return str
}

func (s TAI64N) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TAI64N) DecodeFromPtr(p capnp.Ptr) TAI64N {
	return TAI64N(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TAI64N) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TAI64N) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TAI64N) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TAI64N) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TAI64N) Seconds() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s TAI64N) SetSeconds(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s TAI64N) Nanoseconds() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s TAI64N) SetNanoseconds(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// TAI64N_List is a list of TAI64N.
type TAI64N_List = capnp.StructList[TAI64N]

// NewTAI64N creates a new list of TAI64N.
func NewTAI64N_List(s *capnp.Segment, sz int32) (TAI64N_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[TAI64N](l), err
}

// TAI64N_Future is a wrapper for a TAI64N promised by a client call.
type TAI64N_Future struct{ *capnp.Future }

func (f TAI64N_Future) Struct() (TAI64N, error) {
	p, err := f.Future.Ptr()
	return TAI64N(p.Struct()), err
}

type Node capnp.Struct
type Node_payload Node
type Node_payload_Which uint16

const (
	Node_payload_Which_file       Node_payload_Which = 0
	Node_payload_Which_dir        Node_payload_Which = 1
	Node_payload_Which_volumeLink Node_payload_Which = 2
)

func (w Node_payload_Which) String() string {
	const s = "filedirvolumeLink"
	switch w {
	case Node_payload_Which_file:
		return s[0:4]
	case Node_payload_Which_dir:
		return s[4:7]
	case Node_payload_Which_volumeLink:
		return s[7:17]

	}
	return "Node_payload_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Node_TypeID is the unique identifier for the type Node.
const Node_TypeID = 0xce73733f540a13ee

func NewNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return Node(st), err
}

func NewRootNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return Node(st), err
}

func ReadRootNode(msg *capnp.Message) (Node, error) {
	root, err := msg.Root()
	return Node(root.Struct()), err
}

func (s Node) String() string {
	str, _ := text.Marshal(0xce73733f540a13ee, capnp.Struct(s))
	return str
}

func (s Node) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Node) DecodeFromPtr(p capnp.Ptr) Node {
	return Node(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Node) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Node) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node) CreatedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return TAI64N(p.Struct()), err
}

func (s Node) HasCreatedAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Node) SetCreatedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCreatedAt sets the createdAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Node) NewCreatedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node) ModifiedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TAI64N(p.Struct()), err
}

func (s Node) HasModifiedAt() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Node) SetModifiedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewModifiedAt sets the modifiedAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Node) NewModifiedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node) RefCount() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Node) SetRefCount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Node) Rev() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Node) SetRev(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Node) Mode() uint32 {
	return capnp.Struct(s).Uint32(16)
}

func (s Node) SetMode(v uint32) {
	capnp.Struct(s).SetUint32(16, v)
}

func (s Node) Payload() Node_payload { return Node_payload(s) }

func (s Node_payload) Which() Node_payload_Which {
	return Node_payload_Which(capnp.Struct(s).Uint16(4))
}
func (s Node_payload) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node_payload) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node_payload) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node_payload) File() (File, error) {
	if capnp.Struct(s).Uint16(4) != 0 {
		panic("Which() != file")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return File(p.Struct()), err
}

func (s Node_payload) HasFile() bool {
	if capnp.Struct(s).Uint16(4) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetFile(v File) error {
	capnp.Struct(s).SetUint16(4, 0)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewFile sets the file field to a newly
// allocated File struct, preferring placement in s's segment.
func (s Node_payload) NewFile() (File, error) {
	capnp.Struct(s).SetUint16(4, 0)
	ss, err := NewFile(capnp.Struct(s).Segment())
	if err != nil {
		return File{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node_payload) Dir() (Dir, error) {
	if capnp.Struct(s).Uint16(4) != 1 {
		panic("Which() != dir")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return Dir(p.Struct()), err
}

func (s Node_payload) HasDir() bool {
	if capnp.Struct(s).Uint16(4) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetDir(v Dir) error {
	capnp.Struct(s).SetUint16(4, 1)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewDir sets the dir field to a newly
// allocated Dir struct, preferring placement in s's segment.
func (s Node_payload) NewDir() (Dir, error) {
	capnp.Struct(s).SetUint16(4, 1)
	ss, err := NewDir(capnp.Struct(s).Segment())
	if err != nil {
		return Dir{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node_payload) VolumeLink() (VolumeLink, error) {
	if capnp.Struct(s).Uint16(4) != 2 {
		panic("Which() != volumeLink")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return VolumeLink(p.Struct()), err
}

func (s Node_payload) HasVolumeLink() bool {
	if capnp.Struct(s).Uint16(4) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetVolumeLink(v VolumeLink) error {
	capnp.Struct(s).SetUint16(4, 2)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewVolumeLink sets the volumeLink field to a newly
// allocated VolumeLink struct, preferring placement in s's segment.
func (s Node_payload) NewVolumeLink() (VolumeLink, error) {
	capnp.Struct(s).SetUint16(4, 2)
	ss, err := NewVolumeLink(capnp.Struct(s).Segment())
	if err != nil {
		return VolumeLink{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Node_List is a list of Node.
type Node_List = capnp.StructList[Node]

// NewNode creates a new list of Node.
func NewNode_List(s *capnp.Segment, sz int32) (Node_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3}, sz)
	return capnp.StructList[Node](l), err
}

// Node_Future is a wrapper for a Node promised by a client call.
type Node_Future struct{ *capnp.Future }

func (f Node_Future) Struct() (Node, error) {
	p, err := f.Future.Ptr()
	return Node(p.Struct()), err
}
func (p Node_Future) CreatedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(0, nil)}
}
func (p Node_Future) ModifiedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(1, nil)}
}
func (p Node_Future) Payload() Node_payload_Future { return Node_payload_Future{p.Future} }

// Node_payload_Future is a wrapper for a Node_payload promised by a client call.
type Node_payload_Future struct{ *capnp.Future }

func (f Node_payload_Future) Struct() (Node_payload, error) {
	p, err := f.Future.Ptr()
	return Node_payload(p.Struct()), err
}
func (p Node_payload_Future) File() File_Future {
	return File_Future{Future: p.Future.Field(2, nil)}
}
func (p Node_payload_Future) Dir() Dir_Future {
	return Dir_Future{Future: p.Future.Field(2, nil)}
}
func (p Node_payload_Future) VolumeLink() VolumeLink_Future {
	return VolumeLink_Future{Future: p.Future.Field(2, nil)}
}

type Dir capnp.Struct

// Dir_TypeID is the unique identifier for the type Dir.
const Dir_TypeID = 0xd32874a2d92eaae5

func NewDir(s *capnp.Segment) (Dir, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Dir(st), err
}

func NewRootDir(s *capnp.Segment) (Dir, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Dir(st), err
}

func ReadRootDir(msg *capnp.Message) (Dir, error) {
	root, err := msg.Root()
	return Dir(root.Struct()), err
}

func (s Dir) String() string {
	str, _ := text.Marshal(0xd32874a2d92eaae5, capnp.Struct(s))
	return str
}

func (s Dir) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Dir) DecodeFromPtr(p capnp.Ptr) Dir {
	return Dir(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Dir) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Dir) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Dir) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Dir) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Dir_List is a list of Dir.
type Dir_List = capnp.StructList[Dir]

// NewDir creates a new list of Dir.
func NewDir_List(s *capnp.Segment, sz int32) (Dir_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Dir](l), err
}

// Dir_Future is a wrapper for a Dir promised by a client call.
type Dir_Future struct{ *capnp.Future }

func (f Dir_Future) Struct() (Dir, error) {
	p, err := f.Future.Ptr()
	return Dir(p.Struct()), err
}

type File capnp.Struct

// File_TypeID is the unique identifier for the type File.
const File_TypeID = 0xa54866ce4ae19c91

func NewFile(s *capnp.Segment) (File, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return File(st), err
}

func NewRootFile(s *capnp.Segment) (File, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return File(st), err
}

func ReadRootFile(msg *capnp.Message) (File, error) {
	root, err := msg.Root()
	return File(root.Struct()), err
}

func (s File) String() string {
	str, _ := text.Marshal(0xa54866ce4ae19c91, capnp.Struct(s))
	return str
}

func (s File) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (File) DecodeFromPtr(p capnp.Ptr) File {
	return File(capnp.Struct{}.DecodeFromPtr(p))
}

func (s File) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s File) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s File) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s File) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s File) Size() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s File) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s File) BlockSize() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s File) SetBlockSize(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// File_List is a list of File.
type File_List = capnp.StructList[File]

// NewFile creates a new list of File.
func NewFile_List(s *capnp.Segment, sz int32) (File_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[File](l), err
}

// File_Future is a wrapper for a File promised by a client call.
type File_Future struct{ *capnp.Future }

func (f File_Future) Struct() (File, error) {
	p, err := f.Future.Ptr()
	return File(p.Struct()), err
}

type VolumeLink capnp.Struct

// VolumeLink_TypeID is the unique identifier for the type VolumeLink.
const VolumeLink_TypeID = 0xaaf625b443435e37

func NewVolumeLink(s *capnp.Segment) (VolumeLink, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VolumeLink(st), err
}

func NewRootVolumeLink(s *capnp.Segment) (VolumeLink, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VolumeLink(st), err
}

func ReadRootVolumeLink(msg *capnp.Message) (VolumeLink, error) {
	root, err := msg.Root()
	return VolumeLink(root.Struct()), err
}

func (s VolumeLink) String() string {
	str, _ := text.Marshal(0xaaf625b443435e37, capnp.Struct(s))
	return str
}

func (s VolumeLink) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VolumeLink) DecodeFromPtr(p capnp.Ptr) VolumeLink {
	return VolumeLink(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VolumeLink) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VolumeLink) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VolumeLink) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VolumeLink) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VolumeLink) NodeID() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s VolumeLink) HasNodeID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VolumeLink) SetNodeID(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s VolumeLink) Oid() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s VolumeLink) HasOid() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s VolumeLink) SetOid(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// VolumeLink_List is a list of VolumeLink.
type VolumeLink_List = capnp.StructList[VolumeLink]

// NewVolumeLink creates a new list of VolumeLink.
func NewVolumeLink_List(s *capnp.Segment, sz int32) (VolumeLink_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[VolumeLink](l), err
}

// VolumeLink_Future is a wrapper for a VolumeLink promised by a client call.
type VolumeLink_Future struct{ *capnp.Future }

func (f VolumeLink_Future) Struct() (VolumeLink, error) {
	p, err := f.Future.Ptr()
	return VolumeLink(p.Struct()), err
}

type Session capnp.Struct

// Session_TypeID is the unique identifier for the type Session.
const Session_TypeID = 0x8261a2e190180149

func NewSession(s *capnp.Segment) (Session, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Session(st), err
}

func NewRootSession(s *capnp.Segment) (Session, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Session(st), err
}

func ReadRootSession(msg *capnp.Message) (Session, error) {
	root, err := msg.Root()
	return Session(root.Struct()), err
}

func (s Session) String() string {
	str, _ := text.Marshal(0x8261a2e190180149, capnp.Struct(s))
	return str
}

func (s Session) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Session) DecodeFromPtr(p capnp.Ptr) Session {
	return Session(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Session) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Session) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Session) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Session) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Session) CreateAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return TAI64N(p.Struct()), err
}

func (s Session) HasCreateAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Session) SetCreateAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCreateAt sets the createAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Session) NewCreateAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Session) Ttl() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Session) SetTtl(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Session) PublicKeyRef() (Ref, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Ref(p.Struct()), err
}

func (s Session) HasPublicKeyRef() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Session) SetPublicKeyRef(v Ref) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPublicKeyRef sets the publicKeyRef field to a newly
// allocated Ref struct, preferring placement in s's segment.
func (s Session) NewPublicKeyRef() (Ref, error) {
	ss, err := NewRef(capnp.Struct(s).Segment())
	if err != nil {
		return Ref{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Session) TouchedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return TAI64N(p.Struct()), err
}

func (s Session) HasTouchedAt() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Session) SetTouchedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewTouchedAt sets the touchedAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Session) NewTouchedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Session) LockCount() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s Session) SetLockCount(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// Session_List is a list of Session.
type Session_List = capnp.StructList[Session]

// NewSession creates a new list of Session.
func NewSession_List(s *capnp.Segment, sz int32) (Session_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Session](l), err
}

// Session_Future is a wrapper for a Session promised by a client call.
type Session_Future struct{ *capnp.Future }

func (f Session_Future) Struct() (Session, error) {
	p, err := f.Future.Ptr()
	return Session(p.Struct()), err
}
func (p Session_Future) CreateAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(0, nil)}
}
func (p Session_Future) PublicKeyRef() Ref_Future {
	return Ref_Future{Future: p.Future.Field(1, nil)}
}
func (p Session_Future) TouchedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(2, nil)}
}

type LockState capnp.Struct

// LockState_TypeID is the unique identifier for the type LockState.
const LockState_TypeID = 0xdf8b3ff610d06e84

func NewLockState(s *capnp.Segment) (LockState, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return LockState(st), err
}

func NewRootLockState(s *capnp.Segment) (LockState, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return LockState(st), err
}

func ReadRootLockState(msg *capnp.Message) (LockState, error) {
	root, err := msg.Root()
	return LockState(root.Struct()), err
}

func (s LockState) String() string {
	str, _ := text.Marshal(0xdf8b3ff610d06e84, capnp.Struct(s))
	return str
}

func (s LockState) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LockState) DecodeFromPtr(p capnp.Ptr) LockState {
	return LockState(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LockState) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s LockState) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LockState) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LockState) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s LockState) Holder() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s LockState) HasHolder() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LockState) SetHolder(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s LockState) Kind() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s LockState) SetKind(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

func (s LockState) Start() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s LockState) SetStart(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s LockState) Length() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s LockState) SetLength(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// LockState_List is a list of LockState.
type LockState_List = capnp.StructList[LockState]

// NewLockState creates a new list of LockState.
func NewLockState_List(s *capnp.Segment, sz int32) (LockState_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[LockState](l), err
}

// LockState_Future is a wrapper for a LockState promised by a client call.
type LockState_Future struct{ *capnp.Future }

func (f LockState_Future) Struct() (LockState, error) {
	p, err := f.Future.Ptr()
	return LockState(p.Struct()), err
}

type Ref capnp.Struct

// Ref_TypeID is the unique identifier for the type Ref.
const Ref_TypeID = 0xf5abf3a701595ebc

func NewRef(s *capnp.Segment) (Ref, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Ref(st), err
}

func NewRootRef(s *capnp.Segment) (Ref, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Ref(st), err
}

func ReadRootRef(msg *capnp.Message) (Ref, error) {
	root, err := msg.Root()
	return Ref(root.Struct()), err
}

func (s Ref) String() string {
	str, _ := text.Marshal(0xf5abf3a701595ebc, capnp.Struct(s))
	return str
}

func (s Ref) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Ref) DecodeFromPtr(p capnp.Ptr) Ref {
	return Ref(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Ref) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Ref) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Ref) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Ref) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Ref) Cid() (UInt256, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return UInt256(p.Struct()), err
}

func (s Ref) HasCid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Ref) SetCid(v UInt256) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCid sets the cid field to a newly
// allocated UInt256 struct, preferring placement in s's segment.
func (s Ref) NewCid() (UInt256, error) {
	ss, err := NewUInt256(capnp.Struct(s).Segment())
	if err != nil {
		return UInt256{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Ref) Dek() (UInt256, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return UInt256(p.Struct()), err
}

func (s Ref) HasDek() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Ref) SetDek(v UInt256) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewDek sets the dek field to a newly
// allocated UInt256 struct, preferring placement in s's segment.
func (s Ref) NewDek() (UInt256, error) {
	ss, err := NewUInt256(capnp.Struct(s).Segment())
	if err != nil {
		return UInt256{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Ref_List is a list of Ref.
type Ref_List = capnp.StructList[Ref]

// NewRef creates a new list of Ref.
func NewRef_List(s *capnp.Segment, sz int32) (Ref_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Ref](l), err
}

// Ref_Future is a wrapper for a Ref promised by a client call.
type Ref_Future struct{ *capnp.Future }

func (f Ref_Future) Struct() (Ref, error) {
	p, err := f.Future.Ptr()
	return Ref(p.Struct()), err
}
func (p Ref_Future) Cid() UInt256_Future {
	return UInt256_Future{Future: p.Future.Field(0, nil)}
}
func (p Ref_Future) Dek() UInt256_Future {
	return UInt256_Future{Future: p.Future.Field(1, nil)}
}

type UInt256 capnp.Struct

// UInt256_TypeID is the unique identifier for the type UInt256.
const UInt256_TypeID = 0xee049aba672f50cf

func NewUInt256(s *capnp.Segment) (UInt256, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return UInt256(st), err
}

func NewRootUInt256(s *capnp.Segment) (UInt256, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return UInt256(st), err
}

func ReadRootUInt256(msg *capnp.Message) (UInt256, error) {
	root, err := msg.Root()
	return UInt256(root.Struct()), err
}

func (s UInt256) String() string {
	str, _ := text.Marshal(0xee049aba672f50cf, capnp.Struct(s))
	return str
}

func (s UInt256) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UInt256) DecodeFromPtr(p capnp.Ptr) UInt256 {
	return UInt256(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UInt256) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UInt256) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UInt256) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UInt256) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UInt256) A() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s UInt256) SetA(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s UInt256) B() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s UInt256) SetB(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s UInt256) C() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s UInt256) SetC(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s UInt256) D() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s UInt256) SetD(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

// UInt256_List is a list of UInt256.
type UInt256_List = capnp.StructList[UInt256]

// NewUInt256 creates a new list of UInt256.
func NewUInt256_List(s *capnp.Segment, sz int32) (UInt256_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[UInt256](l), err
}

// UInt256_Future is a wrapper for a UInt256 promised by a client call.
type UInt256_Future struct{ *capnp.Future }

func (f UInt256_Future) Struct() (UInt256, error) {
	p, err := f.Future.Ptr()
	return UInt256(p.Struct()), err
}

const schema_8bfbc7e27592cd31 = "x\xda\x84U]h\x1cU\x14>\xdf\xbd\xb3;\xa9\xa4" +
	"\xecNf\x85>X\x8a\xa5B[\xfa\xff\xa7\x16\xeb6" +
	"MZM\x8d57i\xfd)R\xdc\xdd\xb9\x9b\x8c;" +
	";\xb3\xec\xce&\xa4X\xa2\xc1BM}h\xc4\x82)" +
	"\x0d\x98`i\x1b\x0b\xa2D\xd1\xa2\x0f\x82 (VE" +
	"|\xc8\x83J\x05\xf1\xc9\xbeH\x0b\":r\xf7\x7f7" +
	"[|;\x9c9\xf7\xfc|\xdf\xf9\xcel\xfb\x88\xed\xd7" +
	"\xb6\xaf\xdc\x1a\"&\x1e\x09\x85\x83>\xac:ws>" +
	"1I\xa2\x13\x08\xb6\x7f\xf3F\xf1\xd7/\xff>K!" +
	"\xae\x13\x99\xa7\xd8\xbcy\x9a\xe9D;_ak@\x08" +
	"\x9e\x9a\xfa\xf9\xf6\x1f\x8b\xa3\xb3dt\xb2z0\xc1\x9c" +
	"\xe3\x0b\xe6\xd5\xd2\x9bK|\x98\x10L_\xbcy\xf8F" +
	"\xfa\xf1K*mC\xa4\xa6\"\xbe\xe7S\xe6R)\xf6" +
	"G>F\x08\x1e<\xd1\xd3\xb3\xf8\xc0\x9d\x052:\x1b" +
	";Pu\xcd\xdd\xdaus_\xe9\xd5\xc3\x9a\x8a\xbd\xfc" +
	"\xd8\xa3\xd9\xbf\x0e.}A\xc2\x00\x0fn\x99\xf7\x1c\x8d" +
	"\x17\x0a7\xe8\x18\xd7\xc1\xc1\xcc\xf3\xdaW\x04sF{" +
	"\x8f\x10\xac\xbb\xb2mS:o~\xdd\xae\x85\xdd\xa1\x0b" +
	"\xe6\xbeP)mH\xa5\xad%\x12\x9d\xe0\xad(\xcc\x84" +
	"\xa6\xcc9\x15\xbcs6\xf4\x8cB\xe1\xb7\x85-K\xf3" +
	"\xfe\xfa\x1f\x9a\x1b.%^\x0aO\x9a?\x85u\xe2\xc1" +
	"\xab\xeew\xd1;\xf1\xb3\xbf\xb4\xa6\x84\x0a\xfb$\xfc\x81" +
	"\xf9yXY\x9f\x85\x7f'\x04\xdf\x0el\x1d\xbe~A" +
	"\xbb\xa5\x82\xb5\x96\x94\xd3\xfa\xbc9\xa3+\xeb\xbc\xaeb" +
	"?=\xf1\x1c.\xff\xf9\xee\xedvp\xd9\x1d\x93f\xb6" +
	"\xa3l\x8d\xd1\xe6`L&\xd3\x85-\xa9\x04rnn" +
	"\xef\x90,\x14t\xdbs\x07\x00\x11\xe3\x1a\x91\x06\"\xe3" +
	"\xd4a\"\xf1\x12\x878\xc3\x00\xc4\xa0|\xa7\xd7\x12\x89" +
	"\x979\xc4\xeb\x0c\x06C\x0c\x8c\xc8x\xedE\"q\x86" +
	"C\xbc\xc9`p\x16\x03'2\xa6\x07\x89\xc49\x0eq" +
	"\x91\xc1\xd0\x10\x83Fd\xcc(\xe7[\x1c\xe2\x1d\x86 " +
	"\x95\x97\x09_v\xfbD\x84h\x9d\x14\x02\xa2\x04\xdd\xf7" +
	"\x1dt\x10C\x07!\xc8\x15\x93\x8e\x9dzBRd|" +
	"P\xa6\x11\xadOZ\x0e\x0e|\xaf\x98\x1a\x91V7\xc1" +
	"_\x9e*p\xbcT\xa6\xc7+\xba\xeak5e\xd3\xfc" +
	"G\xc7s2\xd2\xe3YR\x01\x10-\xcd\xb4\xe1\x80z" +
	"m\xdc\x9f$\x023V\xaf%\x027\xee=N4Q" +
	"t3\xae7\xe6\x06y9\\t\x12\xf9C\xa4\xdb\x8e" +
	"\xd4-;\x1f\x8czN1+\xfbm\xe2n\xa6\xb9\xc0" +
	"!\xdb\x91D*{G\x0d\xde\x0d\x1b\x89\xc4:\x0e\xb1" +
	"\x8d\xc1\x00+\xe3\xbbY\x01\xb4\x89C<\xc4\x10)\xd8" +
	"'%V\x10\xc3\x0aB\x90TS\x0c\xd9'\x09\xb2\xfd" +
	"\x10O{N1\xae\xca\xbb\x99\x96B{\x1b\x0bU\x88" +
	"\xdc\xac\x88\\\xcf!v1\xc4]\xcf\x92}\xbdXI" +
	"\x0c+\x09\xbag[U\xbbV\x82\xa9\x12G<Kn" +
	"\xc9%\xc6\x1d/a\x11\x89N\xae\xdd\x17\x04\xacL\xed" +
	"A5\xce~\x0e\xd1\xcf\xb0\x1a\xff*w\x88\xc8\xe8S" +
	"uz9\xc4\x00\xc3j\xf6\x8fr\x87\x89\x8c'\x8f\x13" +
	"\x89~\x0e\xf1,C$m;\x12\xd1\xfae\xa8l\x80" +
	"e\xe7\x11\xadK\xaaBf#\xc8\x88\xd6OD\xe5s" +
	"3\xaf\xdd}{\xf8\xae#-p\x1ch\x87{\xb2\x8e" +
	"\xfbDA\xa6<\xd7*\xd4\xa0w\x13\xae\xa7|\xa4+" +
	"o[\xf0\x152e\x82W\xd5\x0a5.{\x0d\xf79" +
	"5\xf8\xdb\x1c\xe2\x1a\x83*\xaev\xed\xaa\x12\xda\x15\x0e" +
	"\xb1\xa8\xf4\x83\xb2~\xdeW\xc0]\xe3\x10\x1f3 \x84" +
	"\x86\x03g|x\x80\x98\xa1i1u0\x8c\xd9\x8d\xcb" +
	"$u7\x1dd=\xcbN\xdb\xd2\"\xde\xdd\xees^" +
	"\xa6\x95JJz\xac\x0c\xa9\xe7\xe5h\x15\x86\x89\x0a\xf1" +
	"\x91\xacg\xdde\x05{\xed\xbc\xc2\xa0\xd9\xd9\xef\xa52" +
	"k\x86\xfc\x84_VW\x0d\x9e\x84Z\xcb\xe79\xc4H" +
	"\xfd\xbcH5\xcc\x0b\x1c\xc2i8/\xf6\x0e\"aq" +
	"\x88\\\xc3y\xc9\xaa\xd7#\x1c\xc2g\x88\x8fx\x8e%" +
	"\xf3\xd5\x9d\x8ddl\xd7\x82N\x0c:aM\xc1O\xe4" +
	"\xfd\xea\x0cqG\xba\xc3\xfeH\x8d\xd9\xa6F\x8f\xf5\xb9" +
	"\xbe\xbec\xf7\x9e\x966\xbb\xeam\xd6X\x94]\x8d}" +
	"Vh\xb4\xbb\x1a\xfb\xe4\x95>\xbb\xea}\"Q-\x8c" +
	"d\xcdJ\xd5,\xab}[\x832\xddz9\xd6\xfe\x8f" +
	"\xa0\xf5\x94m!Z\xffwT\x05%3\xcb\xbd\xff\x05" +
	"\x00\x00\xff\xffC\x12\xe4\x97"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_8bfbc7e27592cd31,
		Nodes: []uint64{
			0x8261a2e190180149,
			0x9d76b4edf5de8a4f,
			0xa54866ce4ae19c91,
			0xaaf625b443435e37,
			0xc4d945f96d3e47a7,
			0xcb1372662c30a824,
			0xce73733f540a13ee,
			0xd32874a2d92eaae5,
			0xdf8b3ff610d06e84,
			0xee049aba672f50cf,
			0xf5abf3a701595ebc,
		},
		Compressed: true,
	})
}
