// Code generated by capnpc-go. DO NOT EDIT.

package wfscnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type TypeCode uint16

// TypeCode_TypeID is the unique identifier for the type TypeCode.
const TypeCode_TypeID = 0x9d76b4edf5de8a4f

// Values of TypeCode.
const (
	TypeCode_unknown     TypeCode = 0
	TypeCode_regularFile TypeCode = 1
	TypeCode_dir         TypeCode = 2
	TypeCode_volumeLink  TypeCode = 3
)

// String returns the enum's constant name.
func (c TypeCode) String() string {
	switch c {
	case TypeCode_unknown:
		return "unknown"
	case TypeCode_regularFile:
		return "regularFile"
	case TypeCode_dir:
		return "dir"
	case TypeCode_volumeLink:
		return "volumeLink"

	default:
		return ""
	}
}

// TypeCodeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TypeCodeFromString(c string) TypeCode {
	switch c {
	case "unknown":
		return TypeCode_unknown
	case "regularFile":
		return TypeCode_regularFile
	case "dir":
		return TypeCode_dir
	case "volumeLink":
		return TypeCode_volumeLink

	default:
		return 0
	}
}

type TypeCode_List = capnp.EnumList[TypeCode]

func NewTypeCode_List(s *capnp.Segment, sz int32) (TypeCode_List, error) {
	return capnp.NewEnumList[TypeCode](s, sz)
}

type TAI64N capnp.Struct

// TAI64N_TypeID is the unique identifier for the type TAI64N.
const TAI64N_TypeID = 0xcb1372662c30a824

func NewTAI64N(s *capnp.Segment) (TAI64N, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return TAI64N(st), err
}

func NewRootTAI64N(s *capnp.Segment) (TAI64N, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return TAI64N(st), err
}

func ReadRootTAI64N(msg *capnp.Message) (TAI64N, error) {
	root, err := msg.Root()
	return TAI64N(root.Struct()), err
}

func (s TAI64N) String() string {
	str, _ := text.Marshal(0xcb1372662c30a824, capnp.Struct(s))
	return str
}

func (s TAI64N) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TAI64N) DecodeFromPtr(p capnp.Ptr) TAI64N {
	return TAI64N(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TAI64N) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TAI64N) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TAI64N) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TAI64N) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TAI64N) Seconds() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s TAI64N) SetSeconds(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s TAI64N) Nanoseconds() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s TAI64N) SetNanoseconds(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// TAI64N_List is a list of TAI64N.
type TAI64N_List = capnp.StructList[TAI64N]

// NewTAI64N creates a new list of TAI64N.
func NewTAI64N_List(s *capnp.Segment, sz int32) (TAI64N_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[TAI64N](l), err
}

// TAI64N_Future is a wrapper for a TAI64N promised by a client call.
type TAI64N_Future struct{ *capnp.Future }

func (f TAI64N_Future) Struct() (TAI64N, error) {
	p, err := f.Future.Ptr()
	return TAI64N(p.Struct()), err
}

type Node capnp.Struct
type Node_payload Node
type Node_payload_Which uint16

const (
	Node_payload_Which_file       Node_payload_Which = 0
	Node_payload_Which_dir        Node_payload_Which = 1
	Node_payload_Which_volumeLink Node_payload_Which = 2
)

func (w Node_payload_Which) String() string {
	const s = "filedirvolumeLink"
	switch w {
	case Node_payload_Which_file:
		return s[0:4]
	case Node_payload_Which_dir:
		return s[4:7]
	case Node_payload_Which_volumeLink:
		return s[7:17]

	}
	return "Node_payload_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Node_TypeID is the unique identifier for the type Node.
const Node_TypeID = 0xce73733f540a13ee

func NewNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return Node(st), err
}

func NewRootNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return Node(st), err
}

func ReadRootNode(msg *capnp.Message) (Node, error) {
	root, err := msg.Root()
	return Node(root.Struct()), err
}

func (s Node) String() string {
	str, _ := text.Marshal(0xce73733f540a13ee, capnp.Struct(s))
	return str
}

func (s Node) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Node) DecodeFromPtr(p capnp.Ptr) Node {
	return Node(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Node) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Node) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node) CreatedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return TAI64N(p.Struct()), err
}

func (s Node) HasCreatedAt() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Node) SetCreatedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewCreatedAt sets the createdAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Node) NewCreatedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node) ModifiedAt() (TAI64N, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TAI64N(p.Struct()), err
}

func (s Node) HasModifiedAt() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Node) SetModifiedAt(v TAI64N) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewModifiedAt sets the modifiedAt field to a newly
// allocated TAI64N struct, preferring placement in s's segment.
func (s Node) NewModifiedAt() (TAI64N, error) {
	ss, err := NewTAI64N(capnp.Struct(s).Segment())
	if err != nil {
		return TAI64N{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node) RefCount() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Node) SetRefCount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Node) Rev() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Node) SetRev(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Node) Payload() Node_payload { return Node_payload(s) }

func (s Node_payload) Which() Node_payload_Which {
	return Node_payload_Which(capnp.Struct(s).Uint16(4))
}
func (s Node_payload) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node_payload) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node_payload) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node_payload) File() (File, error) {
	if capnp.Struct(s).Uint16(4) != 0 {
		panic("Which() != file")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return File(p.Struct()), err
}

func (s Node_payload) HasFile() bool {
	if capnp.Struct(s).Uint16(4) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetFile(v File) error {
	capnp.Struct(s).SetUint16(4, 0)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewFile sets the file field to a newly
// allocated File struct, preferring placement in s's segment.
func (s Node_payload) NewFile() (File, error) {
	capnp.Struct(s).SetUint16(4, 0)
	ss, err := NewFile(capnp.Struct(s).Segment())
	if err != nil {
		return File{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node_payload) Dir() (Dir, error) {
	if capnp.Struct(s).Uint16(4) != 1 {
		panic("Which() != dir")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return Dir(p.Struct()), err
}

func (s Node_payload) HasDir() bool {
	if capnp.Struct(s).Uint16(4) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetDir(v Dir) error {
	capnp.Struct(s).SetUint16(4, 1)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewDir sets the dir field to a newly
// allocated Dir struct, preferring placement in s's segment.
func (s Node_payload) NewDir() (Dir, error) {
	capnp.Struct(s).SetUint16(4, 1)
	ss, err := NewDir(capnp.Struct(s).Segment())
	if err != nil {
		return Dir{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Node_payload) VolumeLink() (VolumeLink, error) {
	if capnp.Struct(s).Uint16(4) != 2 {
		panic("Which() != volumeLink")
	}
	p, err := capnp.Struct(s).Ptr(2)
	return VolumeLink(p.Struct()), err
}

func (s Node_payload) HasVolumeLink() bool {
	if capnp.Struct(s).Uint16(4) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(2)
}

func (s Node_payload) SetVolumeLink(v VolumeLink) error {
	capnp.Struct(s).SetUint16(4, 2)
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewVolumeLink sets the volumeLink field to a newly
// allocated VolumeLink struct, preferring placement in s's segment.
func (s Node_payload) NewVolumeLink() (VolumeLink, error) {
	capnp.Struct(s).SetUint16(4, 2)
	ss, err := NewVolumeLink(capnp.Struct(s).Segment())
	if err != nil {
		return VolumeLink{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Node_List is a list of Node.
type Node_List = capnp.StructList[Node]

// NewNode creates a new list of Node.
func NewNode_List(s *capnp.Segment, sz int32) (Node_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[Node](l), err
}

// Node_Future is a wrapper for a Node promised by a client call.
type Node_Future struct{ *capnp.Future }

func (f Node_Future) Struct() (Node, error) {
	p, err := f.Future.Ptr()
	return Node(p.Struct()), err
}
func (p Node_Future) CreatedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(0, nil)}
}
func (p Node_Future) ModifiedAt() TAI64N_Future {
	return TAI64N_Future{Future: p.Future.Field(1, nil)}
}
func (p Node_Future) Payload() Node_payload_Future { return Node_payload_Future{p.Future} }

// Node_payload_Future is a wrapper for a Node_payload promised by a client call.
type Node_payload_Future struct{ *capnp.Future }

func (f Node_payload_Future) Struct() (Node_payload, error) {
	p, err := f.Future.Ptr()
	return Node_payload(p.Struct()), err
}
func (p Node_payload_Future) File() File_Future {
	return File_Future{Future: p.Future.Field(2, nil)}
}
func (p Node_payload_Future) Dir() Dir_Future {
	return Dir_Future{Future: p.Future.Field(2, nil)}
}
func (p Node_payload_Future) VolumeLink() VolumeLink_Future {
	return VolumeLink_Future{Future: p.Future.Field(2, nil)}
}

type Dir capnp.Struct

// Dir_TypeID is the unique identifier for the type Dir.
const Dir_TypeID = 0xd32874a2d92eaae5

func NewDir(s *capnp.Segment) (Dir, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Dir(st), err
}

func NewRootDir(s *capnp.Segment) (Dir, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Dir(st), err
}

func ReadRootDir(msg *capnp.Message) (Dir, error) {
	root, err := msg.Root()
	return Dir(root.Struct()), err
}

func (s Dir) String() string {
	str, _ := text.Marshal(0xd32874a2d92eaae5, capnp.Struct(s))
	return str
}

func (s Dir) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Dir) DecodeFromPtr(p capnp.Ptr) Dir {
	return Dir(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Dir) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Dir) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Dir) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Dir) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Dir_List is a list of Dir.
type Dir_List = capnp.StructList[Dir]

// NewDir creates a new list of Dir.
func NewDir_List(s *capnp.Segment, sz int32) (Dir_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Dir](l), err
}

// Dir_Future is a wrapper for a Dir promised by a client call.
type Dir_Future struct{ *capnp.Future }

func (f Dir_Future) Struct() (Dir, error) {
	p, err := f.Future.Ptr()
	return Dir(p.Struct()), err
}

type File capnp.Struct

// File_TypeID is the unique identifier for the type File.
const File_TypeID = 0xa54866ce4ae19c91

func NewFile(s *capnp.Segment) (File, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return File(st), err
}

func NewRootFile(s *capnp.Segment) (File, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return File(st), err
}

func ReadRootFile(msg *capnp.Message) (File, error) {
	root, err := msg.Root()
	return File(root.Struct()), err
}

func (s File) String() string {
	str, _ := text.Marshal(0xa54866ce4ae19c91, capnp.Struct(s))
	return str
}

func (s File) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (File) DecodeFromPtr(p capnp.Ptr) File {
	return File(capnp.Struct{}.DecodeFromPtr(p))
}

func (s File) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s File) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s File) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s File) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s File) Size() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s File) SetSize(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s File) BlockSize() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s File) SetBlockSize(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// File_List is a list of File.
type File_List = capnp.StructList[File]

// NewFile creates a new list of File.
func NewFile_List(s *capnp.Segment, sz int32) (File_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[File](l), err
}

// File_Future is a wrapper for a File promised by a client call.
type File_Future struct{ *capnp.Future }

func (f File_Future) Struct() (File, error) {
	p, err := f.Future.Ptr()
	return File(p.Struct()), err
}

type VolumeLink capnp.Struct

// VolumeLink_TypeID is the unique identifier for the type VolumeLink.
const VolumeLink_TypeID = 0xaaf625b443435e37

func NewVolumeLink(s *capnp.Segment) (VolumeLink, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VolumeLink(st), err
}

func NewRootVolumeLink(s *capnp.Segment) (VolumeLink, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return VolumeLink(st), err
}

func ReadRootVolumeLink(msg *capnp.Message) (VolumeLink, error) {
	root, err := msg.Root()
	return VolumeLink(root.Struct()), err
}

func (s VolumeLink) String() string {
	str, _ := text.Marshal(0xaaf625b443435e37, capnp.Struct(s))
	return str
}

func (s VolumeLink) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VolumeLink) DecodeFromPtr(p capnp.Ptr) VolumeLink {
	return VolumeLink(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VolumeLink) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VolumeLink) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VolumeLink) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VolumeLink) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VolumeLink) NodeID() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s VolumeLink) HasNodeID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VolumeLink) SetNodeID(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s VolumeLink) Oid() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s VolumeLink) HasOid() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s VolumeLink) SetOid(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// VolumeLink_List is a list of VolumeLink.
type VolumeLink_List = capnp.StructList[VolumeLink]

// NewVolumeLink creates a new list of VolumeLink.
func NewVolumeLink_List(s *capnp.Segment, sz int32) (VolumeLink_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[VolumeLink](l), err
}

// VolumeLink_Future is a wrapper for a VolumeLink promised by a client call.
type VolumeLink_Future struct{ *capnp.Future }

func (f VolumeLink_Future) Struct() (VolumeLink, error) {
	p, err := f.Future.Ptr()
	return VolumeLink(p.Struct()), err
}

const schema_8bfbc7e27592cd31 = "x\xdal\x93Oh$E\x18\xc5\xdf\xab\xea\xd9\xce\xca" +
	"\x84L\xd3\xe3\xcd .+\xac\x12c\x16\x17\x95=\x98" +
	"M&\x89&\xc4\x98\xd2(\x92\x83\xd03]\x13\x9a\xe9" +
	"t\x0f=3\x09\x09J\xc0? Q!\x0a\x82J\xbc" +
	"\x08\xa2\xe4\xe2%'o\x82A\xa2LD\xc4C.\x82" +
	"\x82G\xbd)\x88\xc4^j2\x99?an\x1f_=" +
	"\xbe_\xbd\xf7UM\xbc\xc1;\xd6\xcd\xe1\x1f%\x84\x1a" +
	"\xcb\\I\x9f\xdb\xfd\xf5\xef?\x0f7>\x85\x93\x15\xe9" +
	"\xcd\xe6\x07\x8d\xdf\xbf\xfb\xef\x1d\x80n\x93\x07\xee/\xb4" +
	"\x01\xf7'\xae\x81\xe9\xfb\xfb\xbf-\x9c\x94\x9f\xf9\x1c*" +
	"\xcb\x1e\xa5e\x14g\xdcu3\xc2T\x14\x9b`\xfa\xc4" +
	"+\x85\xc2\xe1\x83\xff\x1c\xc0\xc9\xb2+=Wx\xe2k" +
	"7hU\xba\xa5\xfd\xe2\xe9\xa7\xd6\xff\x9d=\xfd\x16\xca" +
	"\xa1H\xffr\xefY\x99\xac\xd5N\xf0\xa2\xb4))\xdc" +
	"o\xc4\xf7\xa0{$\xbe\x02\xd3\xeb_N\x8c\x95\x13\xf7" +
	"\x87AW\xf0\xe4'n [c\xa5\x19\xdb\x19\xd4\xaf" +
	"\xcd\xb4$Gr\xd7m\x9a\xea\xb1cy?\xc1\xf4\x8f" +
	"\x83\xf1\xd3\xcf\xea7~\xee\xbfpk\xf0\xb1\xf5\xba\xdb" +
	"\xb4l<\x9an\xeab\xb96^\xf2X\x8d\xaa\xb7W" +
	"\xb6\xaaz\xa4\x10\xfbz\x99T9\x0a\xc0yh\x1a " +
	"\x9d\x07\x8a\x00\x853z\x0d\xa0t\xee]\x05v\x1aQ" +
	"%\x8a7\xa34\xd1k\x8d\xd0K\xe6`\x07\xa1\xb6\xfd" +
	" I7\xe2\xb0\xb1\xae\x17\x03\xc8\xa8\xd2\x0f\x98\x0bB" +
	"\x0d\x98\xe9C\xd2\x02,\x1a\xc2\xc3\x80\xba.\xa9&\x04" +
	"\x1d\x8a<M\xf3\x91\xe7\x015&\xa9\x9e\x14\x1c\xa9\x05" +
	"\xdb\x9aW!x\x15L\x8ba\\\xaa\xbc\x10l\x83\x9a" +
	"C\x10\x1c\x02\xfb\x19/\xc5ac\xd2\xe0\xa3\xca%\xd0" +
	"\xed^\x10\xdb\xa0k\x80\xba!\xa9n\x09NF\xb1\xaf" +
	"\xe7g8\x0c\xc1a\xd0\x8e\x03\xff\xa2\xee \x84A," +
	"\xc5\xbe\x1e\xafz[a\xec\xf9\x80\xcaJ\xeb\xbe4\x15" +
	"yZ\x803k\xec\xdc\x91T\x8b\x82\xa3\xfc\xdf\xb43" +
	"\x803o83\x92jYpT\x9c\x99\xf6\x15\xc0y" +
	"v\x15P\x8b\x92\xeae\xc1\x91r\x10j\xe6\xba\x8f\x12" +
	"d\x0e4\x912\xd7\xdd\xe6y\xb7/d\xe6\xba\xaf\xb3" +
	"}\xdc\xbf\xd7\xa9\xf9\xc7\xe5\xad\xa5KqL\x0f\xca\xbd" +
	"\xd8\xcd}\xa7\xa6Kq\xe4\xd7:\xd1G^\x14\x9b\x1e" +
	"l\xd3\x1d\x18\xbeI\xe6|\xc1\xf9\x0e\xe85\xb3\xcbW" +
	"%\xd5\xdb=\xb9\xbfe\x8c\xbf)\xa9\xf6\x04\x0d\xdc\xbc" +
	"\xb5\xf7\x16\x00\xf5\xae\xa4\xfaH\xd0\x91\xccS\x02\xce\x87" +
	"&\xb8=I\xb5/H\x8b=\x7f\xcb\xf9x\x1a\"-" +
	"%\xda\xabk\x7f\x0a\xac3\xd7\xfdM\xed\x18\xd6c?" +
	"(\x07\xda\x87\x9c\x1at\x9c\xe8r!nDu\x00\x17" +
	"~\xecDo\\8\xdei\xef\xb8\xdf\xe3L\x90\x18\x87" +
	"w\x03\x00\x00\xff\xffl%\"\xd6"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_8bfbc7e27592cd31,
		Nodes: []uint64{
			0x9d76b4edf5de8a4f,
			0xa54866ce4ae19c91,
			0xaaf625b443435e37,
			0xc4d945f96d3e47a7,
			0xcb1372662c30a824,
			0xce73733f540a13ee,
			0xd32874a2d92eaae5,
		},
		Compressed: true,
	})
}
